In [40]:
# Import required libraries
import pandas as pd
from sqlalchemy import create_engine, text
from sqlalchemy.exc import SQLAlchemyError
import os
from dotenv import load_dotenv
import warnings
warnings.filterwarnings('ignore')

# Load environment variables
load_dotenv()

print("Libraries imported successfully!")

Libraries imported successfully!

In [41]:
# Database connection configuration to SAKIP
DB_HOST = os.getenv('DB_HOST_SAKIP', 'localhost')
DB_PORT = os.getenv('DB_PORT_SAKIP', '5432')  # PostgreSQL default port
DB_NAME = os.getenv('DB_DATABASE_SAKIP', 'your_database_name')
DB_USER = os.getenv('DB_USERNAME_SAKIP', 'your_username')
DB_PASSWORD = os.getenv('DB_PASSWORD_SAKIP', 'your_password')

# Create connection string for PostgreSQL
connection_string = f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"

print(f"Connecting to database: {DB_NAME} on {DB_HOST}:{DB_PORT}")
print(f"User: {DB_USER}")

# Test connection
try:
    engine_sakip = create_engine(connection_string, echo=False)
    with engine_sakip.connect() as connection:
        result = connection.execute(text("SELECT 1 as test"))
        print("✅ Database connection successful!")
        print(f"Connection test result: {result.fetchone()[0]}")
except SQLAlchemyError as e:
    print(f"❌ Database connection failed: {e}")
    print("Please check your database credentials in the .env file")

Connecting to database: e-sakip on 10.110.34.49:5432
User: postgres
✅ Database connection successful!
Connection test result: 1

In [42]:
def load_data_from_sql(query, engine):
    """
    Load data from PostgreSQL database into a pandas DataFrame.
    
    Parameters:
    query (str): SQL query to execute
    engine: SQLAlchemy engine object
    
    Returns:
    pandas.DataFrame: Data from the query
    """
    connection = None
    try:
        # Create a new connection and rollback any pending transaction
        connection = engine.connect()
        
        # Rollback any pending transaction to ensure clean state
        try:
            connection.rollback()
        except:
            pass  # If no transaction to rollback, ignore
        
        # Execute the query
        df = pd.read_sql(query, connection)
        print(f"✅ Data loaded successfully! Shape: {df.shape}")
        
        connection.close()
        return df
    except Exception as e:
        # Ensure connection is closed on error
        if connection:
            try:
                connection.rollback()
            except:
                pass
            try:
                connection.close()
            except:
                pass
        print(f"❌ Error loading data: {e}")
        return None

def get_table_info(table_name, engine):
    """
    Get basic information about a table.
    
    Parameters:
    table_name (str): Name of the table
    engine: SQLAlchemy engine object
    """
    try:
        # Get table structure using PostgreSQL information_schema
        structure_query = f"""
            SELECT 
                column_name,
                data_type,
                character_maximum_length,
                is_nullable,
                column_default
            FROM information_schema.columns
            WHERE table_name = '{table_name}'
            ORDER BY ordinal_position
        """
        structure = pd.read_sql(structure_query, engine)
        
        # Get row count
        count_query = f"SELECT COUNT(*) as row_count FROM {table_name}"
        count_result = pd.read_sql(count_query, engine)
        
        print(f"📊 Table: {table_name}")
        print(f"Rows: {count_result['row_count'].iloc[0]}")
        print(f"Columns: {len(structure)}")
        print("\nColumn Information:")
        print(structure)
        
        return structure
    except SQLAlchemyError as e:
        print(f"❌ Error getting table info: {e}")
        return None

def list_tables(engine):
    """
    List all tables in the database.
    
    Parameters:
    engine: SQLAlchemy engine object
    """
    try:
        # Use PostgreSQL information_schema to list tables
        query = """
            SELECT table_name 
            FROM information_schema.tables 
            WHERE table_schema = 'public'
            ORDER BY table_name
        """
        tables = pd.read_sql(query, engine)
        print("📋 Available tables:")
        for table in tables['table_name']:
            print(f"  - {table}")
        return tables
    except SQLAlchemyError as e:
        print(f"❌ Error listing tables: {e}")
        return None

print("Data loading functions defined successfully!")

Data loading functions defined successfully!

In [43]:
query = "SELECT * FROM skp \
WHERE tahun_kinerja = '2026' \
AND is_skp;"

df_skp = pd.DataFrame()

df_skp = load_data_from_sql(query, engine_sakip)

✅ Data loaded successfully! Shape: (7228, 17)

In [44]:
df_skp.head()

,id,tahun_mulai,tahun_kinerja,satuan_kerja_id,pengampu,v_struktur_organisasi_id,tim_kerja_id,model_class,model_id,sasaran,indikator,target,satuan,created_at,updated_at,parent_id,is_skp
0,41652,2025,2026,1003,tim-kerja,None,18047.0,App\Models\KinerjaSubKegiatan,52104,Teridentifikasinya data calon peserta murid baru,Jumlah data calon peserta didik baru,1,dokumen,2026-01-31 20:36:53,2026-01-31 20:36:53,36067.0,True
1,36525,2025,2026,1002,tim-kerja,None,11584.0,App\Models\KinerjaSubKegiatan,45073,Tersusunnya bahan rapat DPRD,jumlah bahan rapat DPRD,2,Dokumen,2026-01-31 20:35:47,2026-01-31 20:35:47,36110.0,True
2,36526,2025,2026,1002,tim-kerja,None,11585.0,App\Models\KinerjaSubKegiatan,45074,Tersusunnya berita acara rapat,Jumlah berita acara rapat,2,Dokumen,2026-01-31 20:35:47,2026-01-31 20:35:47,36110.0,True
3,40810,2025,2026,1020,tim-kerja,None,17886.0,App\Models\KinerjaSubKegiatan,50945,Tersalurkannya Sumur Dalam ditingkat usaha tan...,Jumlah Poktan Tembakau yang menerima bantuan S...,1,Poktan,2026-01-31 20:36:42,2026-01-31 20:36:42,34799.0,True
4,40811,2025,2026,1020,tim-kerja,None,17217.0,App\Models\KinerjaSubKegiatan,50948,Terbinanya penyuluh pertanian tentang perkebunan,Jumlah penyuluh pertanian yang terbina tentang...,20,orang,2026-01-31 20:36:42,2026-01-31 20:36:42,34858.0,True

In [45]:
# Collect tim_kerja_id 

tim_kerja_ids = [str(int(x)) for x in df_skp['tim_kerja_id'].unique() if pd.notnull(x)]

len(tim_kerja_ids)

3423

In [46]:
tim_kerja_ids

['18047',
 '11584',
 '11585',
 '17886',
 '17217',
 '17413',
 '17052',
 '18484',
 '17065',
 '18005',
 '18012',
 '18116',
 '17105',
 '56',
 '17107',
 '18704',
 '17889',
 '17299',
 '17111',
 '16965',
 '17478',
 '17580',
 '17566',
 '18951',
 '20045',
 '20046',
 '18957',
 '17121',
 '17123',
 '12025',
 '19228',
 '18016',
 '17177',
 '19790',
 '18143',
 '18765',
 '19046',
 '18792',
 '17292',
 '17866',
 '17281',
 '17255',
 '17257',
 '17874',
 '19796',
 '17575',
 '19089',
 '15715',
 '251',
 '18534',
 '15738',
 '16933',
 '16932',
 '10866',
 '19634',
 '18789',
 '19631',
 '19791',
 '16957',
 '18634',
 '16587',
 '19723',
 '19254',
 '18368',
 '16757',
 '19246',
 '12639',
 '17523',
 '19242',
 '19244',
 '19331',
 '15751',
 '19279',
 '18485',
 '17481',
 '15473',
 '19230',
 '19236',
 '17482',
 '18980',
 '19660',
 '17137',
 '18483',
 '19281',
 '12610',
 '17153',
 '17157',
 '16580',
 '17160',
 '19764',
 '17168',
 '17702',
 '17176',
 '17483',
 '18616',
 '17582',
 '14960',
 '18788',
 '17170',
 '17171',
 '18576',
 '17181',
 '18579',
 '18575',
 '18559',
 '18480',
 '18451',
 '18435',
 '18450',
 '18448',
 '17184',
 '17185',
 '10221',
 '17186',
 '19195',
 '17180',
 '19217',
 '15667',
 '350',
 '17926',
 '9996',
 '823',
 '17197',
 '19879',
 '6261',
 '16941',
 '7332',
 '16622',
 '19750',
 '15390',
 '15389',
 '18443',
 '18705',
 '16915',
 '12992',
 '19526',
 '19520',
 '17286',
 '12860',
 '12056',
 '12205',
 '12263',
 '2551',
 '19639',
 '17484',
 '17486',
 '12192',
 '18627',
 '18628',
 '2599',
 '18630',
 '18640',
 '18647',
 '16783',
 '18503',
 '17625',
 '18527',
 '18524',
 '17960',
 '17924',
 '17930',
 '17901',
 '18540',
 '17694',
 '9919',
 '17667',
 '17680',
 '11259',
 '17693',
 '10269',
 '17713',
 '17932',
 '17725',
 '12699',
 '11474',
 '17519',
 '17777',
 '17775',
 '9149',
 '17905',
 '17828',
 '17487',
 '17831',
 '17099',
 '17963',
 '17973',
 '18025',
 '18073',
 '18065',
 '18134',
 '18135',
 '18115',
 '18128',
 '18129',
 '9387',
 '8410',
 '17819',
 '18495',
 '17747',
 '18493',
 '18542',
 '17149',
 '11478',
 '17768',
 '17892',
 '17865',
 '17984',
 '18060',
 '18139',
 '18122',
 '9392',
 '17369',
 '17640',
 '18750',
 '11780',
 '17477',
 '8321',
 '12277',
 '17785',
 '18535',
 '17492',
 '11748',
 '17951',
 '18537',
 '18754',
 '18011',
 '17288',
 '17145',
 '17753',
 '17789',
 '17755',
 '18019',
 '17397',
 '17542',
 '16308',
 '7652',
 '10426',
 '18182',
 '18188',
 '9600',
 '18707',
 '19120',
 '1934',
 '16158',
 '17863',
 '17230',
 '17231',
 '17233',
 '17234',
 '17235',
 '17237',
 '17251',
 '17256',
 '17263',
 '17267',
 '17272',
 '18475',
 '17517',
 '18771',
 '17820',
 '17298',
 '5105',
 '17318',
 '17319',
 '17320',
 '17321',
 '17322',
 '17323',
 '17324',
 '17326',
 '17327',
 '17328',
 '18945',
 '17330',
 '20009',
 '17332',
 '19040',
 '17333',
 '17334',
 '18948',
 '17579',
 '17335',
 '17336',
 '17337',
 '17339',
 '17341',
 '17520',
 '19013',
 '17342',
 '19015',
 '17343',
 '17345',
 '19016',
 '17346',
 '17347',
 '17348',
 '17349',
 '17350',
 '17352',
 '20008',
 '19041',
 '19043',
 '17354',
 '19062',
 '17750',
 '19003',
 '19004',
 '17357',
 '17358',
 '17360',
 '17363',
 '17364',
 '17365',
 '17675',
 '18492',
 '18517',
 '17379',
 '17380',
 '18339',
 '18338',
 '18415',
 '17391',
 '16857',
 '17394',
 '17396',
 '17399',
 '17401',
 '17402',
 '17438',
 '17403',
 '19094',
 '17404',
 '19263',
 '17408',
 '17407',
 '17406',
 '17409',
 '19260',
 '17412',
 '17417',
 '8714',
 '17416',
 '17415',
 '17418',
 '19264',
 '17419',
 '13265',
 '17420',
 '17421',
 '19258',
 '17422',
 '17423',
 '17424',
 '17425',
 '18685',
 '17426',
 '17427',
 '17429',
 '17428',
 '17430',
 '17432',
 '17433',
 '17434',
 '17435',
 '19697',
 '17437',
 '17508',
 '17439',
 '17510',
 '19216',
 '19409',
 '17444',
 '17445',
 '19280',
 '17446',
 '17447',
 '18974',
 '18976',
 '17451',
 '19339',
 '17453',
 '17454',
 '17457',
 '17459',
 '18972',
 '17460',
 '18794',
 '17462',
 '17463',
 '59',
 '19580',
 '19579',
 '19570',
 '19574',
 '19569',
 '19585',
 '17195',
 '10592',
 '19227',
 '19091',
 '19224',
 '19959',
 '19831',
 '19957',
 '14347',
 '18032',
 '19832',
 '16497',
 '18711',
 '3784',
 '19203',
 '18212',
 '19042',
 '19044',
 '15969',
 '16945',
 '17485',
 '17993',
 '18553',
 '17852',
 '17854',
 '2183',
 '5091',
 '8923',
 '13547',
 '13559',
 '5778',
 '9049',
 '19495',
 '19667',
 '17183',
 '9995',
 '19541',
 '18601',
 '16946',
 '19670',
 '17294',
 '18772',
 '18775',
 '18773',
 '19673',
 '19669',
 '9998',
 '15935',
 '19668',
 '6300',
 '19397',
 '19671',
 '19641',
 '10599',
 '16083',
 '18359',
 '16085',
 '16086',
 '19973',
 '16115',
 '18915',
 '16102',
 '18927',
 '16112',
 '18923',
 '18894',
 '10290',
 '16082',
 '16084',
 '18360',
 '16092',
 '16113',
 '18916',
 '18925',
 '16110',
 '18891',
 '18892',
 '18856',
 '18863',
 '18357',
 '18880',
 '15993',
 '18919',
 '18933',
 '16189',
 '16188',
 '16190',
 '15979',
 '16186',
 '19149',
 '9990',
 '19962',
 '18581',
 '20005',
 '20024',
 '19998',
 '15953',
 '15950',
 '15961',
 '15955',
 '8101',
 '17996',
 '20000',
 '19128',
 '16947',
 '19348',
 '20004',
 '18798',
 '19730',
 '19640',
 '13667',
 '15940',
 '15944',
 '18554',
 '19145',
 '19214',
 '15948',
 '19357',
 '19371',
 '19867',
 '19436',
 '19354',
 '19369',
 '19853',
 '19952',
 '19935',
 '19437',
 '19863',
 '19909',
 '19823',
 '19992',
 '12969',
 '19365',
 '20003',
 '20006',
 '20025',
 '19999',
 '19894',
 '19855',
 '19896',
 '19373',
 '19954',
 '19393',
 '11925',
 '8668',
 '786',
 '16496',
 '16236',
 '9452',
 '6306',
 '16383',
 '18797',
 '19119',
 '15925',
 '15920',
 '15923',
 '15924',
 '19381',
 '20020',
 '19674',
 '6083',
 '19025',
 '19001',
 '20002',
 '9453',
 '19395',
 '17995',
 '15964',
 '15361',
 '11354',
 '6301',
 '19394',
 '2904',
 '12903',
 '12906',
 '19401',
 '19148',
 '12507',
 '15986',
 '16124',
 '18358',
 '19975',
 '18291',
 '19672',
 '16167',
 '18937',
 '16171',
 '16174',
 '19126',
 '6458',
 '19404',
 '16144',
 '16041',
 '16042',
 '16043',
 '19951',
 '16080',
 '16058',
 '18931',
 '18930',
 '16076',
 '16079',
 '16073',
 '16064',
 '18899',
 '16068',
 '15982',
 '16016',
 '18361',
 '19974',
 '16038',
 '18917',
 '18929',
 '18928',
 '19928',
 '19936',
 '19933',
 '16030',
 '16117',
 '16116',
 '6304',
 '17832',
 '19396',
 '19132',
 '10257',
 '10255',
 '6307',
 '11923',
 '19362',
 '19399',
 '15922',
 '15928',
 '11723',
 '13586',
 '13542',
 '9662',
 '12028',
 '12248',
 '16973',
 '19315',
 '12085',
 '19320',
 '12084',
 '19333',
 '12244',
 '12886',
 '12251',
 '12250',
 '19326',
 '16653',
 '17974',
 '16056',
 '19849',
 '6668',
 '11749',
 '19257',
 '17937',
 '9991',
 '19429',
 '19170',
 '14382',
 '19922',
 '19129',
 '5131',
 '19996',
 '18714',
 '16191',
 '16192',
 '15962',
 '16002',
 '16003',
 '16193',
 '16200',
 '12916',
 '18934',
 '16199',
 '16197',
 '18904',
 '18286',
 '13550',
 '18777',
 '18583',
 '8614',
 '18223',
 '16658',
 '9999',
 '19156',
 '18720',
 '3100',
 '7979',
 '17994',
 '18471',
 '7956',
 '16650',
 '18555',
 '16619',
 '13223',
 '15926',
 '17431',
 '810',
 '2980',
 '19197',
 '18281',
 '19205',
 '19157',
 '19206',
 '19207',
 '19020',
 '18402',
 '18604',
 '19406',
 '19030',
 '19031',
 '19158',
 '19604',
 '19691',
 '19762',
 '20019',
 '19971',
 '19532',
 '19765',
 '19690',
 '19829',
 '13351',
 '12776',
 '16427',
 '19752',
 '19923',
 '19352',
 '15551',
 '19483',
 '14661',
 '19784',
 '14799',
 '3284',
 '16362',
 '58',
 '13466',
 '15056',
 '14803',
 '15051',
 '7501',
 '13282',
 '8804',
 '19584',
 '13354',
 '19319',
 '18778',
 '19305',
 '8453',
 '18887',
 '14013',
 '17511',
 '19111',
 '14209',
 '11579',
 '19441',
 '4003',
 '15880',
 '19509',
 '19486',
 '18582',
 '19451',
 '14679',
 '19338',
 '19578',
 '19500',
 '18858',
 '20041',
 '19165',
 '19009',
 '19014',
 '9333',
 '16322',
 '19085',
 '11953',
 '7544',
 '12503',
 '18006',
 '18881',
 '14595',
 '14693',
 '16913',
 '19141',
 '2912',
 '19905',
 '10094',
 '19941',
 '14781',
 '4812',
 '11625',
 '14184',
 '15838',
 '14740',
 '19994',
 '19890',
 '18652',
 '13464',
 '19695',
 '11583',
 '14437',
 '14135',
 '17962',
 '19659',
 '19656',
 '19886',
 '18731',
 '14682',
 '18897',
 '13708',
 '19938',
 '15231',
 '17395',
 '19946',
 '19317',
 '13218',
 '19234',
 '11994',
 '14301',
 '19565',
 '11564',
 '9595',
 '14765',
 '13397',
 '19282',
 '14594',
 '8686',
 '2888',
 '14226',
 '19571',
 '19418',
 '19420',
 '15277',
 '8474',
 '19978',
 '18910',
 '14164',
 '14676',
 '15468',
 '19101',
 '14450',
 '7529',
 '14175',
 '18238',
 '8950',
 '19817',
 '19653',
 '18431',
 '19921',
 '12212',
 '18735',
 '14632',
 '17885',
 '19322',
 '16917',
 '13137',
 '18552',
 '19364',
 '18477',
 '18568',
 '18447',
 '18440',
 '19540',
 '18594',
 '19870',
 '19917',
 '16132',
 '19573',
 '18200',
 '15193',
 '19742',
 '14649',
 '11878',
 '19523',
 '19828',
 '19285',
 '19008',
 '19754',
 '19572',
 '16146',
 '15556',
 '19294',
 '14397',
 '14805',
 '19587',
 '13732',
 '14604',
 '18424',
 '18848',
 '18374',
 '19349',
 '13002',
 '17472',
 '11395',
 '13044',
 '18363',
 '19461',
 '14613',
 '14698',
 '14062',
 '13809',
 '3798',
 '13216',
 '12644',
 '17821',
 '18844',
 '15876',
 '14879',
 '16921',
 '18730',
 '14305',
 '18816',
 '11570',
 '14673',
 '19271',
 '11334',
 '19278',
 '15564',
 '18650',
 '18913',
 '18429',
 '19029',
 '18712',
 '14158',
 '18189',
 '19002',
 '13638',
 '19969',
 '19878',
 '19827',
 '19328',
 '6451',
 '18921',
 '18823',
 '12914',
 '12452',
 '18938',
 '19795',
 '11954',
 '19822',
 '17466',
 '8809',
 '18924',
 '19444',
 '18278',
 '18737',
 '19968',
 '18736',
 '18852',
 '18408',
 '12407',
 '19533',
 '18799',
 '18868',
 '19558',
 '13590',
 '7540',
 '13756',
 '13033',
 '15983',
 '12975',
 '19734',
 '15811',
 '14011',
 '18985',
 '15547',
 '14836',
 '19273',
 '19664',
 '14211',
 '18909',
 '14442',
 '18847',
 '19353',
 '15553',
 '14314',
 '15404',
 '11706',
 '17649',
 '14744',
 '14449',
 '15597',
 '10277',
 '19685',
 '14311',
 '14664',
 '12638',
 '13760',
 '11568',
 '11575',
 '6807',
 '10288',
 '14103',
 '14061',
 '14060',
 '14043',
 '14045',
 '17609',
 '18926',
 '13024',
 '19000',
 '14411',
 '14313',
 '18708',
 ...]

In [47]:
# Database connection configuration to TRK 2026
DB_HOST_2026 = os.getenv('DB_HOST_2026', 'localhost')
DB_PORT_2026 = os.getenv('DB_PORT_2026', '5432')  # PostgreSQL default port
DB_NAME_2026 = os.getenv('DB_DATABASE_2026', 'your_database_name')
DB_USER_2026 = os.getenv('DB_USERNAME_2026', 'your_username')
DB_PASSWORD_2026 = os.getenv('DB_PASSWORD_2026', 'your_password')

# Create connection string for PostgreSQL
connection_string = f"postgresql+psycopg2://{DB_USER_2026}:{DB_PASSWORD_2026}@{DB_HOST_2026}:{DB_PORT_2026}/{DB_NAME_2026}"

print(f"Connecting to database: {DB_NAME_2026} on {DB_HOST_2026}:{DB_PORT_2026}")
print(f"User: {DB_USER_2026}")

# Test connection
try:
    engine_2026 = create_engine(connection_string, echo=False)
    with engine_2026.connect() as connection:
        result = connection.execute(text("SELECT 1 as test"))
        print("✅ Database connection successful!")
        print(f"Connection test result: {result.fetchone()[0]}")
except SQLAlchemyError as e:
    print(f"❌ Database connection failed: {e}")
    print("Please check your database credentials in the .env file")

Connecting to database: erk_ekinerja_2026 on 10.110.32.114:5432
User: postgres
✅ Database connection successful!
Connection test result: 1

In [48]:
# Collect data from tim_kerja
query = "SELECT * FROM tim_kerja \
WHERE id IN ('" + "', '".join(tim_kerja_ids) + "')"

df_tim_kerja = pd.DataFrame()

df_tim_kerja = load_data_from_sql(query, engine_2026)

✅ Data loaded successfully! Shape: (3423, 8)

In [49]:
df_tim_kerja.head()

,id,nama,satuan_kerja_id,v_struktur_organisasi_id,nip_ketua,created_at,updated_at,deleted_at
0,54,Pencegahan Dampak Lingkungan,1034,103407030000,197306121998032013,2022-01-31 13:17:50,2022-01-31 13:17:50,None
1,56,"Pengendalian Sampah, B3 dan Limbah B3",1034,103407030000,197807302006042005,2022-01-31 13:36:30,2022-01-31 13:36:30,None
2,58,Pengendalian Pencemaran Air dan Udara,1034,103407030000,197701142009011001,2022-01-31 13:46:00,2022-01-31 13:46:00,None
3,59,Konservasi Lingkungan dan Keanekaragaman Hayati,1034,103407030000,198007152011012001,2022-01-31 13:55:02,2022-01-31 13:55:02,None
4,60,Pengembangan Kapasitas dan Kemitraan,1034,103407030000,197909122011012001,2022-01-31 13:58:22,2022-01-31 13:58:22,None

In [63]:
# Collect nip_ketua
nip_ketuas = df_tim_kerja['nip_ketua'].unique()

nip_ketuas.tolist()

['197306121998032013',
 '197807302006042005',
 '197701142009011001',
 '198007152011012001',
 '197909122011012001',
 '197908122006042006',
 '197309121998031004',
 '198008112010011002',
 '198011142011012003',
 '197306282008011003',
 '196903172002121001',
 '196806141997031004',
 '198201122001121004',
 '198001262011011002',
 '199208142014061001',
 '197902212008012003',
 '197603112014122001',
 '198010202010011003',
 '197103022005011010',
 '198211132008082001',
 '197606162008011004',
 '197011251998031005',
 '198609202010012006',
 '197504281999022001',
 '197902162011011001',
 '197410032008012003',
 '198007042011011001',
 '197411241999031005',
 '196902261989031004',
 '197402152006041009',
 '197409032009011001',
 '197108101997022005',
 '197005231998031007',
 '197608162005011011',
 '197904102011011002',
 '196705171990111001',
 '197410262008012003',
 '197601242006042004',
 '198108232005011008',
 '197709022009012001',
 '199709232020121009',
 '197606162009011004',
 '197707282005011006',
 '198209042009011001',
 '198611062004122002',
 '198702232011012002',
 '197810212011012002',
 '197109281999032008',
 '196903102007011010',
 '196906291991021001',
 '199705302020121011',
 '197311052003122004',
 '198008042010012003',
 '199803142022031014',
 '199003032020122012',
 '198006132010011008',
 '199105252014021002',
 '199408152020122021',
 '197910272008012003',
 '197106281998031007',
 '196710311990032004',
 '197002052008012009',
 '196702181996032001',
 '196810191999012001',
 '198106282003122002',
 '197008041998032002',
 '197210061998032005',
 '196711062000031003',
 '197403241999032002',
 '197108151998032010',
 '197311172007011006',
 '197904302008011002',
 '198404192010011009',
 '196811081998032002',
 '197902132010011001',
 '198004122011012001',
 '197607152007012010',
 '197206012007011003',
 '199306152017081001',
 '198710052015032006',
 '198102032010012002',
 '197307042007011005',
 '197810081998031003',
 '197306032008011005',
 '197906202008011004',
 '197001011994031014',
 '198306232006042011',
 '199405162017081003',
 '198308272010121002',
 '199111042014021002',
 '198503282011011003',
 '196903241999011001',
 '198406052010012014',
 '199508302017081002',
 '198512172010012008',
 '197512262005011002',
 '198112112010012008',
 '198405242015031006',
 '197811252010011009',
 '197303081998032008',
 '199207282015071002',
 '197101241997022003',
 '197003091991031007',
 '198203052009022002',
 '198603152010011002',
 '198905082020121009',
 '198509302010012003',
 '197602242006041006',
 '197606072009032002',
 '197206251999032002',
 '197810012011012009',
 '196702221993031007',
 '198211072011012005',
 '198604172011011005',
 '198611032011011002',
 '199711132019082001',
 '198908172015031003',
 '200007012022021001',
 '197105012005011006',
 '197207152005012001',
 '198112072010011002',
 '197701032009011005',
 '199303202015071002',
 '199408222016091001',
 '199604152022031010',
 '197312221999032005',
 '197607292007012007',
 '198604302007012001',
 '198608202010011007',
 '198903102015032004',
 '197607102014121002',
 '199201172020122016',
 '196812091988032003',
 '199107092012062001',
 '198003032001122002',
 '197507132000031004',
 '198205172010012001',
 '199206072020122015',
 '198501122020122005',
 '197702031999012001',
 '196810031994031006',
 '196902032007012007',
 '197208111994042001',
 '196812161992031004',
 '198811092020121005',
 '196909031994032001',
 '196612051993032002',
 '197105262000032004',
 '196908092007012007',
 '197104222007012003',
 '196707041992022002',
 '197108022008011002',
 '198701132010011003',
 '197911232010012005',
 '196805271994032006',
 '197506121998031004',
 '196806121990092002',
 '197409132008011003',
 '196910221998031003',
 '198801272020122003',
 '197611252009021001',
 '198010022006042015',
 '197603042010012002',
 '199505252020122036',
 '197608142008011002',
 '197510172008011002',
 '198601102010012015',
 '198707242010012004',
 '197501142009012004',
 '197912242010011002',
 '197608102006042023',
 '197607022011011003',
 '198404232010011012',
 '199308022020122017',
 '197510232009012001',
 '197907261998101001',
 '197312292008011003',
 '198312312010011024',
 '199403132020122020',
 '197409102008011005',
 '197010162007011006',
 '196911302008011002',
 '197201271999011001',
 '197203191997031003',
 '199011092012061001',
 '196809241993102001',
 '198111252010012007',
 '198004282009011002',
 '197709072008011006',
 '196902121994011001',
 '198010262000031002',
 '198911242011011001',
 '197405192009011002',
 '196711241996032002',
 '196912252005011009',
 '196606031996031002',
 '197001122009012001',
 '199704042019031001',
 '197509272006042005',
 '197309302014122001',
 '197101202005011008',
 '197403101998031005',
 '198205042010011010',
 '199412302020122021',
 '198407142009021001',
 '198707232011011003',
 '197806232005012001',
 '199407202020121005',
 '197503012007011007',
 '197107081998032004',
 '199706112022031011',
 '198310292010011002',
 '196906021998031004',
 '196712151994031010',
 '199604052020121006',
 '196712051993031009',
 '197412062007011008',
 '196905041998032007',
 '198902012011012005',
 '198202032006042008',
 '197204092009011001',
 '196902281999031002',
 '196609112008011001',
 '196703221997032001',
 '197408291994031006',
 '196905231994032005',
 '197309221999032004',
 '199110112015071001',
 '197605031998031003',
 '199711252020122010',
 '198005122010011012',
 '198801082015031004',
 '197805081997031001',
 '198210232005011004',
 '196902261993031003',
 '197206062006042008',
 '197411101994031008',
 '198011202008011005',
 '198603202011012003',
 '197307272008011005',
 '198108202000031002',
 '197102112014122001',
 '197002062001121002',
 '197004202003121003',
 '197612131997031005',
 '196906211991031001',
 '197412052000121002',
 '197410091995031001',
 '197407132006041004',
 '197212142006041003',
 '198709092020121007',
 '197208291999011001',
 '198712302015031003',
 '197401092010011003',
 '198508292020122004',
 '198201022010011014',
 '198411162009021001',
 '197311202005011005',
 '199011162015071001',
 '197112242009011001',
 '197412232009011001',
 '197612012014071001',
 '198303282011012003',
 '197405021994031002',
 '198404282011011006',
 '198510262010012008',
 '198608232015031003',
 '197104011998031010',
 '197005141998031004',
 '198309042015031001',
 '198309182011011001',
 '198808302011011003',
 '197705172009011001',
 '198107192010011009',
 '198301142010011014',
 '198207122005012016',
 '196906201998031003',
 '198010112005012001',
 '197812112005012001',
 '197403012008121001',
 '197812082009011003',
 '197609302005012006',
 '197107101998032007',
 '197608102011011003',
 '198604082009022005',
 '199105022020121008',
 '196701301998031002',
 '198010192008011002',
 '197602272009011002',
 '196905301992031007',
 '198101312011011001',
 '197108202008011004',
 '197508042007011005',
 '197204212008011003',
 '197002111992031008',
 '197111121998032003',
 '199404082020122028',
 '199202132020122019',
 '197102032005011009',
 '197204122007012004',
 '198310032011011003',
 '197105252002121007',
 '197907282009011001',
 '197008101992031010',
 '197710242006041006',
 '198912292020122011',
 '197007041998031002',
 '197412232009022003',
 '197506051996031002',
 '198704292015031003',
 '198201192009022001',
 '199403182020122016',
 '198701222020122009',
 '197007292008011004',
 '197102211996032002',
 '199608192020121009',
 '199403232020122016',
 '197108091998031003',
 '197608152010011004',
 '197901012009022003',
 '198006221999031001',
 '197709132009011001',
 '197410192000031003',
 '198010192010012007',
 '198409042011012005',
 '197804142008011003',
 '197006232000031002',
 '197504272008012006',
 '197611112014121003',
 '197403312008011002',
 '198508032010011008',
 '198103092006042013',
 '197408101996031003',
 '197911102009011001',
 '197903072009011007',
 '197708072009021001',
 '197807162009021003',
 '197102031997031006',
 '196810131999031003',
 '198310282009021003',
 '197401102008011005',
 '198309042005011001',
 '197909111998031002',
 '197405192006041004',
 '197211172006041007',
 '197705132009011002',
 '196811041999031003',
 '197305062006041013',
 '197210202008011003',
 '198509072010011012',
 '197106021998031006',
 '197011042007012006',
 '197804262009021001',
 '197305072008011001',
 '198004212009022001',
 '198111262011011001',
 '199203072020121012',
 '197402142005012006',
 '198109262005012017',
 '198103192014121001',
 '197610282009011004',
 '197606062008011006',
 '199404152019031008',
 '197212012010011001',
 '197108032006041013',
 '197010221990031001',
 '197108021998031006',
 '199406032016091002',
 '198006292010011008',
 '198206302009121001',
 '199501272017082001',
 '198407182010012020',
 '197911242014112001',
 '197308192002122001',
 '198107022009012002',
 '196808112002121008',
 '197512232010012001',
 '197408222006042013',
 '197709272008011003',
 '197707282008011004',
 '197210142005021002',
 '197003111997031004',
 '197008242002121001',
 '197812292009011002',
 '197606042008011003',
 '199701152018081001',
 '197902022010011007',
 '197609091996031004',
 '197908222000031001',
 '196912141991031004',
 '198403052015032004',
 '198308052011011004',
 '197304181997031004',
 '198711072015031002',
 '197605232006041006',
 '198206062010011013',
 '197203212006041001',
 '197903222002121002',
 '196906151994031017',
 '196904101998031008',
 '197306271994031003',
 '199112162012061001',
 '197312051996021002',
 '197601022003122006',
 '199404022020121012',
 '197604042005012009',
 '199110292015031003',
 '198804292011012003',
 '197303202006042004',
 '196904091998031007',
 '196807071990031008',
 '197503152008011004',
 '197502271998031002',
 '197002062008011004',
 '197012111996031003',
 '198211072010011002',
 '198103252011012004',
 '197607041997031002',
 '198109022015032001',
 '197610012005011010',
 '199511162017081001',
 '197807262008011004',
 '197308081999032005',
 '197905022005012012',
 '198208112015032002',
 '198303142009021002',
 '198608212010012008',
 '197308122006041006',
 '197308271998032003',
 '197509071999012001',
 '197601012008011005',
 '199405062020121011',
 '199409102020121008',
 '197501172009011001',
 '197411282009011002',
 '197412022009022001',
 '199510292020121006',
 '196906291999011001',
 '197506272003122001',
 '197009071995032002',
 '196802221994031009',
 '197203301999031002',
 '197211071999011001',
 '197102062008011003',
 '196907152008011005',
 '197503042010011003',
 '198404152003121001',
 '197410221998031005',
 '197802032009011004',
 '196911222007011007',
 '197802202010011001',
 '197204071996031002',
 '197506252008012003',
 '198103222008011003',
 '197112131994031001',
 '197405091998032002',
 '196808051999031003',
 '197307312009011001',
 '197212231998032006',
 '198203112001122001',
 '198507202011011004',
 '197201161999012001',
 '197204031999021001',
 '196906221998031007',
 '197107041998032005',
 '198501022010012018',
 '197809072009012001',
 '197705182010011012',
 '197501282009022004',
 '197905082008011012',
 '198004162006041006',
 '198103102009022002',
 '197501071998111001',
 '198110262009011001',
 '197805152009011003',
 '197607172009011004',
 '197901242010011004',
 '198604172011011007',
 '199212302022032006',
 '196909051999011001',
 '197511101998031003',
 '196907191995032004',
 '196907272008012010',
 '196901031993032009',
 '197706301998031002',
 '197307151998032005',
 '197703212009011003',
 '197302192009012002',
 '198111152009021001',
 '197011071998031007',
 '198406182010011007',
 '197603062007011008',
 '197202102002121003',
 '196907251994032007',
 '197112301992031002',
 '197708261999032002',
 '197310092008011003',
 '196812031989031008',
 '198005122010011004',
 '198409262011011003',
 '199401122016091001',
 '198105242010012009',
 '198003172000031003',
 '197703091998031003',
 '199305072020122024',
 '196904062008011003',
 '197908062008011002',
 '196810201991031007',
 '199011022022032005',
 '197111271998031004',
 '199409082020121008',
 '197103161998031006',
 '198604142010011007',
 '199203042023211011',
 '198409032011011001',
 '197604232009022002',
 '199608072022031018',
 '197508171996031003',
 '197810262010011003',
 '199406062020122035',
 '197606012003121003',
 '198103202011012002',
 '199201192022031006',
 '199108032020121014',
 '198204192010011011',
 '199403262017081001',
 '199408222016091002',
 '198411212011011001',
 '196901151998031005',
 '196910151994031006',
 '197507211998032003',
 '196910121993022003',
 '197110081997032006',
 '197702282000032003',
 '196912092005012001',
 '197306052005011013',
 '197208041998031008',
 '197901232010011001',
 '197106012006041004',
 '197312101994032005',
 '197001221996032002',
 '197209281995011001',
 '199606042020122019',
 '199611032019082001',
 '198104132009021004',
 '199105132020121017',
 '197403052007011010',
 '199011152020122020',
 '198106212011011002',
 '198310272009011005',
 '198201262010011004',
 '197412062014121001',
 '197409062014122001',
 '196706101991021002',
 '196708271990031008',
 '198306112011011002',
 '198910222020121003',
 '198108242006041001',
 '198808212022032006',
 '197412182008011004',
 '196812231988032002',
 '199812082022031005',
 '199006112022031004',
 '198911222022031003',
 '197402062008012010',
 '197403112008011001',
 '196807191993032005',
 '197302142008011002',
 '198909162015031004',
 '196812011998031006',
 '196908171996031010',
 '197703262006042009',
 '197512072010011003',
 '197402231993031001',
 '198304082009022008',
 '199001122015032007',
 '197408032005011001',
 '198711292010012008',
 '197007131997032002',
 '197506162007011007',
 '198012202010011014',
 '197905232010011006',
 '198006172009021002',
 '196812221998031006',
 '196704091989032005',
 '197005121997031008',
 '196908151996031002',
 '196807051992031008',
 '197605292006042008',
 '196710141998032002',
 '197803032010011008',
 '196709161988021002',
 '197302221995101001',
 '197107131999032003',
 '196812031998031005',
 '197209061998031004',
 '197412302000032005',
 '197006161998031006',
 '199512272020122015',
 '197009041998032006',
 '197108021998031008',
 '196710151998031003',
 '197112261998031009',
 '197006241998031008',
 '197003051998031006',
 '197307281994031001',
 '197107062006041004',
 '196702151998032003',
 '196802181998031006',
 '196909111998031006',
 '196909131998032007',
 '196905101998031009',
 '197001241998031004',
 '197207142000032005',
 '196912271998031008',
 '196811251998031005',
 '196904261998031006',
 '196809272007011004',
 '196704151998031007',
 '196803301998031004',
 '196804171998031007',
 '196911141998031006',
 '196709291998031007',
 '196612041998031006',
 '196802091998031005',
 '196911111998031010',
 '197208171998031007',
 '196710201998031005',
 '197105031998031008',
 '197511242009021002',
 '199208222014062001',
 '196801161992032006',
 '197310171998031004',
 '199112262015032003',
 '199608192022032018',
 '196804072000031003',
 '197111131998031003',
 '197006231998032006',
 '199007082015031001',
 '196904061998031004',
 '197203051998031007',
 '197506132000032009',
 '196711051998031002',
 '196709121998031006',
 '196906111998032001',
 '197010251998031010',
 '198010142007012003',
 '197006191998031007',
 '196703131998031008',
 '197905032005011009',
 '197210011998032005',
 '198911102020121011',
 '198008021998101001',
 '198610032010011012',
 '199301112016091002',
 '199310102020121014',
 '198411282011011002',
 '199009222020122017',
 '197408282006041011',
 '197108131998031005',
 '197401102006041003',
 '198512272014021001',
 '199305252020121013',
 '197802122009012002',
 '198707072014021002',
 '197004281997032004',
 '198705022020121006',
 '197205252006041004',
 '199602032019082001',
 '197312021999032003',
 '198304032011011003',
 '199107082020121006',
 '197204232014121003',
 '197001182006042006',
 '198711152011011002',
 '199610102020121008',
 '197107102007011010',
 '197805282008011004',
 '197709182014111001',
 '199103172020121015',
 '199306182020122014',
 '198505312011011005',
 '197810042005011007',
 '197106282008011002',
 '198101082011011002',
 '198007062007012011',
 '198001242003121003',
 '199408212016092001',
 '196808291989032002',
 '196609081994031005',
 '197311062014121001',
 '197805072007011008',
 '197008022007011014',
 '197508032009011002',
 '198011182011011001',
 '198306032002121001',
 '197811132009011004',
 '199505272020121023',
 '197611142008011004',
 '197811222010012001',
 '198612202020121005',
 '198007042010011002',
 '198603182010012009',
 '197812302009011001',
 '199112122015071003',
 '198105122014121001',
 '198002172006041005',
 '197908112014111001',
 '198007022009021001',
 '199508062022031007',
 '199512192018081002',
 '200009032022021001',
 '200002072022021001',
 '197304072008011003',
 '198501012011011004',
 '197908012014102001',
 '198012182015032001',
 '198201302009011003',
 '197805242008012009',
 '197109012007011004',
 '197603022002122006',
 '198601052015031003',
 '197208262007011004',
 '197701101996122001',
 '199211122020121014',
 '197601292009021001',
 '198909052019031005',
 '199612142020121010',
 '199210112015031003',
 '197312122005011010',
 '197208212005012006',
 '198303252015031002',
 '199209012020121011',
 '197808082008012015',
 '197907102008012036',
 '197310222000032001',
 '197105191993111001',
 '196706261994032006',
 '200009102022021001',
 '199106072014062001',
 '196902042008011001',
 '197212292008012002',
 '197808172010012002',
 '198309212010012005',
 '197504071999032002',
 '197803192007012008',
 '198610232011011002',
 '197203311998032003',
 '198207062009012001',
 '197811142008012003',
 '198102082009021003',
 '197502202008012005',
 '198801092020122009',
 '199505072020122017',
 '197710022006042011',
 '198904272014032001',
 '197806062005011008',
 '197910132014091002',
 '198508192010011007',
 '197107171993031007',
 '199612272020122013',
 '196712131992031005',
 '197204152000121003',
 '197111201998021002',
 '198503022009021002',
 '198302172006042011',
 '198011202008012001',
 '197407032005012008',
 '197510102008011005',
 '199409052016091001',
 '198006302009012001',
 '198108032014072001',
 '197606132010012002',
 '197606282008012004',
 '198110062009012002',
 '198005242010011004',
 '196904031992081001',
 '198912122015021001',
 '199003102020122010',
 '198706012010121001',
 '198006242023211002',
 '197609072009021003',
 '197610062011011001',
 '197505102006042007',
 '197012131992032006',
 '198508242011011002',
 '199305092015072002',
 '198708252011012003',
 '196901082007012003',
 '197510152014122001',
 '197101312007012002',
 '198807222020121006',
 '198101042011012002',
 '198702182011011001',
 '198110312011012001',
 '198010042009022001',
 '197008242007012005',
 '197802132008012005',
 '198901102020122007',
 '198710192011011001',
 '199311082019032014',
 '197809022010012001',
 '197606202006042007',
 '197704122009011003',
 '197409102010012003',
 '198110142014121003',
 '197507072006041013',
 '198403142011011001',
 '197109081998032004',
 '197706062010011001',
 '197007161993032005',
 '198106112010012014',
 '199705262020122014',
 '197002251992121001',
 '199611182020121005',
 '196608061993031004',
 '199204112014061001',
 '197906192010011008',
 '196910051989032004',
 '199701242022032021',
 '197808182014092001',
 '198108112014121001',
 '199408012020121016',
 '198603222011012005',
 '198104072011011001',
 '197311092007011005',
 '197904292010012005',
 '196909112007011007',
 '199407022020122016',
 '196906141997021003',
 '197906202005011002',
 '198607172015031002',
 '197212312008011017',
 '197612102006042005',
 '199207152020121017',
 '196811271990031003',
 '199705302020121009',
 '198204112008012004',
 '197502122007011006',
 '199810112022032013',
 '198411232009121002',
 '197010132008012006',
 '196508181993031001',
 '197310152006041011',
 '197902032008011004',
 '198008172009011002',
 '197303021992032002',
 '199009142014021002',
 '196909191999012001',
 '199404172020122018',
 '198101152009021002',
 '199410172020121010',
 '196712011992111001',
 '196901081994031003',
 '196901091991032009',
 '197512162006041002',
 '198204052010011002',
 '198703202015031006',
 '197003071993032002',
 '197911262011012002',
 '199311222015071001',
 '199109072020121010',
 '197208182014122005',
 '199510092020121011',
 '198903072012061001',
 '196807121991032006',
 '197405251999032016',
 '198303172009122001',
 '197210051993031006',

In [62]:
nip_jpts_str = '197011111991021001,196904201988032004,196906121988031002,196812161998031003,197010151991031004,197606121996031005,197306171993031004,197912182005011008,196704211992031013,198311172006041009,196704061994022002,197603021997011001,198109252010011010,198202142006041004,197306241998031008,197804191996121001,197307071999022001,198409112002121001,197309182005011004,197302222001121003,197108252005012009,197808112003121005,196607101993031005,197404051998031012,197812222006042009,196610201998031003,197201162002122002,196706301998032005,198008292000031002,197409261998032005,197503171999012001,197204191998031007,196610271987021002,197709172002122004,197203181998031007,196710111993031009,197403051997031003,197808062008011003,197211061999012001,197805052005011016,196703191994031001,197212181998031008,196609111994022001,197108131997031007,196707291993031004,196804041988032014,197909171998101001,197312121993031002,197009221998031004,197108121998032006,196812221996011001,196906232006041004,197509132006041008,197906281998101001'

nip_jpts_list = nip_jpts_str.split(',')

nip_jpts_list

['197011111991021001',
 '196904201988032004',
 '196906121988031002',
 '196812161998031003',
 '197010151991031004',
 '197606121996031005',
 '197306171993031004',
 '197912182005011008',
 '196704211992031013',
 '198311172006041009',
 '196704061994022002',
 '197603021997011001',
 '198109252010011010',
 '198202142006041004',
 '197306241998031008',
 '197804191996121001',
 '197307071999022001',
 '198409112002121001',
 '197309182005011004',
 '197302222001121003',
 '197108252005012009',
 '197808112003121005',
 '196607101993031005',
 '197404051998031012',
 '197812222006042009',
 '196610201998031003',
 '197201162002122002',
 '196706301998032005',
 '198008292000031002',
 '197409261998032005',
 '197503171999012001',
 '197204191998031007',
 '196610271987021002',
 '197709172002122004',
 '197203181998031007',
 '196710111993031009',
 '197403051997031003',
 '197808062008011003',
 '197211061999012001',
 '197805052005011016',
 '196703191994031001',
 '197212181998031008',
 '196609111994022001',
 '197108131997031007',
 '196707291993031004',
 '196804041988032014',
 '197909171998101001',
 '197312121993031002',
 '197009221998031004',
 '197108121998032006',
 '196812221996011001',
 '196906232006041004',
 '197509132006041008',
 '197906281998101001']

In [53]:
# Collect non null v_struktur_organisasi_id
v_struktur_organisasi_ids = df_tim_kerja['v_struktur_organisasi_id'].dropna().unique()

len(v_struktur_organisasi_ids)

399

In [54]:
# Database connection configuration to SIMPEG
DB_HOST_SIMPEG = os.getenv('DB_HOST_SIMPEG', 'localhost')
DB_PORT_SIMPEG = os.getenv('DB_PORT_SIMPEG', '5432')  # PostgreSQL default port
DB_NAME_SIMPEG = os.getenv('DB_DATABASE_SIMPEG', 'your_database_name')
DB_USER_SIMPEG = os.getenv('DB_USERNAME_SIMPEG', 'your_username')
DB_PASSWORD_SIMPEG = os.getenv('DB_PASSWORD_SIMPEG', 'your_password')

# Create connection string for PostgreSQL
connection_string = f"postgresql+psycopg2://{DB_USER_SIMPEG}:{DB_PASSWORD_SIMPEG}@{DB_HOST_SIMPEG}:{DB_PORT_SIMPEG}/{DB_NAME_SIMPEG}"

print(f"Connecting to database: {DB_NAME_SIMPEG} on {DB_HOST_SIMPEG}:{DB_PORT_SIMPEG}")
print(f"User: {DB_USER_SIMPEG}")

# Test connection
try:
    engine_simpeg = create_engine(connection_string, echo=False)
    with engine_simpeg.connect() as connection:
        result = connection.execute(text("SELECT 1 as test"))
        print("✅ Database connection successful!")
        print(f"Connection test result: {result.fetchone()[0]}")
except SQLAlchemyError as e:
    print(f"❌ Database connection failed: {e}")
    print("Please check your database credentials in the .env file")

Connecting to database: simpeg_jabar on 10.110.32.121:5432
User: postgres
✅ Database connection successful!
Connection test result: 1

In [56]:

query = (
    "SELECT * FROM m_spg_jabatan "
    "WHERE unit_kerja_id IN ('" + "', '".join(v_struktur_organisasi_ids) + "') "
    "AND jfu_id is null AND jf_id is null"
)

df_m_spg_jabatan = pd.DataFrame()

df_m_spg_jabatan = load_data_from_sql(query, engine_simpeg)

df_m_spg_jabatan.head()

✅ Data loaded successfully! Shape: (381, 20)

,jabatan_id,jfu_id,satuan_kerja_id,unit_kerja_id,jabkat_id,gol_id_awal,gol_id_akhir,jf_id,eselon_id,jabatan_nama,jabatan_jenis,jabatan_type,kode_jabatan,jabatan_kelas,jabatan_bup,created_at,updated_at,create_username,update_username,deleted_at
0,10003,None,1001,100101010000,None,None,None,None,22,KEPALA BIRO PEMERINTAHAN DAN OTONOMI DAERAH,2,None,3.07.01.01.01,14,60,NaT,2019-05-27 03:02:28.517172,None,None,NaT
1,10004,None,1001,100101010100,None,None,None,None,31,KEPALA BAGIAN PEMERINTAHAN,2,None,3.07.01.01.01.01,None,58,NaT,2019-05-27 03:02:28.517172,None,exclude_distribusi_skp,2023-12-18
2,10008,None,1001,100101010200,None,None,None,None,31,KEPALA BAGIAN OTONOMI DAERAH,2,None,3.07.01.01.01.02,None,58,NaT,2019-05-27 03:02:28.517172,None,exclude_distribusi_skp,2023-12-18
3,100041205,None,1001,100101010400,None,None,None,None,31,KEPALA BAGIAN TATA USAHA,2,None,3.07.01.01.01.04,12,58,NaT,2022-08-19 04:32:39.650408,None,None,NaT
4,10016,None,1001,100101020000,None,None,None,None,22,KEPALA BIRO HUKUM DAN HAK ASASI MANUSIA,2,None,3.07.01.01.02,14,60,NaT,2019-05-27 03:02:28.517172,None,None,NaT

In [ ]:
# Collect jabatan_id
jabatan_ids = df_m_spg_jabatan['jabatan_id'].unique()

len(jabatan_ids)

381

In [59]:
# Collect pegawais with jabatan_id
query = "SELECT * FROM spg_pegawai \
WHERE jabatan_id IN ('" + "', '".join(str(x) for x in jabatan_ids) + "')"

df_spg_pegawai = pd.DataFrame()

df_spg_pegawai = load_data_from_sql(query, engine_simpeg)

df_spg_pegawai.head()

✅ Data loaded successfully! Shape: (581, 118)

,peg_id,id_goldar,gol_id_awal,id_pend_awal,unit_kerja_id,kecamatan_id,gol_id_akhir,jabatan_id,id_pend_akhir,id_agama,...,peg_pppk_tmt,sk_cpns_tanggal,sk_pns_tanggal,peg_kk,no_sk_udin,no_sk_pi,sk_udin_tanggal,sk_pi_tanggal,peg_no_bpjs_ketenagakerjaan,formasi
0,198409112002121001,4.0,131.0,136.0,100101010000,None,142,10003,12,1.0,...,None,2003-01-02,2004-01-02,3273070202150014,None,None,None,None,None,None
1,197306241998031008,4.0,131.0,293.0,100101020000,None,143,10016,12,1.0,...,None,1998-04-20,1999-04-12,3217020103070001,None,None,None,None,None,None
2,197804191996121001,1.0,131.0,293.0,100101030000,None,143,10029,12,1.0,...,None,None,None,None,None,None,None,None,None,None
3,197302222001121003,2.0,131.0,293.0,100102010000,None,142,10043,12,1.0,...,None,None,None,None,None,None,None,None,None,None
4,198202142006041004,1.0,131.0,293.0,100102020000,None,141,10056,12,1.0,...,None,2006-07-20,2007-09-27,3273161309103677,None,None,None,None,None,None

In [64]:
# Collect nips
nips = df_spg_pegawai['peg_nip'].unique()

nips.tolist()

['198409112002121001',
 '197306241998031008',
 '197804191996121001',
 '197302222001121003',
 '198202142006041004',
 '196801101990031001',
 '197309182005011004',
 '197307071999022001',
 '195901031985031009',
 '198109252010011010',
 '198608112006021001',
 '196803301994031003',
 '198403192009022002',
 '198801062007012001',
 '196711161994031004',
 '196512231990021001',
 '197002281998021002',
 '196501031989031007',
 '197710022009021003',
 '196904091994021001',
 '196312081985031011',
 '197402041993111002',
 '198212282002121002',
 '196407101993031009',
 '197103011998021002',
 '196611151991011002',
 '196503071985122001',
 '196606301988111002',
 '196804071998021002',
 '198408212009011003',
 '196101221981092001',
 '198409072002121001',
 '197001221993032003',
 '198302052002121001',
 '196103281982021002',
 '196506181996031001',
 '196609281993032004',
 '196909111992012001',
 '196806131994032004',
 '196604281987121002',
 '197612022003121004',
 '196709141994031004',
 '197308172000031010',
 '196108151994031001',
 '197202022005012011',
 '196503071990021001',
 '196107131985031011',
 '198104302006041004',
 '197509082010012003',
 '196404141989032007',
 '197202022007012011',
 '196112301990011001',
 '196808181993121001',
 '196211161990032001',
 '196709291994032008',
 '198201032009021004',
 '196509301988031009',
 '196709031990032005',
 '198205072009021004',
 '196601311985031001',
 '198207112009022001',
 '196105211984021002',
 '196802181996032004',
 '198106062006041016',
 '196204121981102002',
 '198103082005012006',
 '196312281996031002',
 '198003152006042009',
 '196410271989031004',
 '197312121996032001',
 '196109091982041003',
 '197709192005012013',
 '196812201991031007',
 '198612052009022004',
 '197111011999021001',
 '196907122001122003',
 '196308071986032011',
 '197911072009022003',
 '196809231992022001',
 '198212292010012015',
 '196604231996031003',
 '197612241996021003',
 '197606252002121002',
 '198006111998101002',
 '196709301996012001',
 '198406202003121001',
 '196409141986031016',
 '197307311998031003',
 '196110031992031002',
 '197306062003121008',
 '196212221989031007',
 '196809062006041004',
 '198308202009021001',
 '198604272011011001',
 '197308211998031002',
 '196806281988031002',
 '197108261991031001',
 '196308201989032005',
 '197608092008011002',
 '196207201989031012',
 '198006052003122006',
 '196902111998032002',
 '196712111991031003',
 '196710051996031001',
 '196206151983031009',
 '197404272006041005',
 '196612251988021001',
 '196903251989031003',
 '196110051986031014',
 '198801082007011001',
 '196107201991032001',
 '197710232005011007',
 '196211281989032002',
 '198304052009121003',
 '196404141991022001',
 '197107132005011007',
 '198007292000121001',
 '197101121998032007',
 '196704281987121001',
 '197905311997111001',
 '196505011992031007',
 '197403261998032002',
 '196508081985031003',
 '198610272010011004',
 '196511101990031007',
 '197603302007011003',
 '196804061997031002',
 '197806202002121002',
 '197108082006041013',
 '198104271999122001',
 '196805071989031006',
 '196405021988092001',
 '196802061998021004',
 '196808041995022002',
 '196411231987032007',
 '196307101992032005',
 '197203121998032004',
 '197104011998031009',
 '196105151985031011',
 '196510181991022002',
 '196804091987031004',
 '196304071986032006',
 '196909031994032001',
 '196402111990032003',
 '196508161994032003',
 '198104252006042011',
 '197808112011012001',
 '197608112006042002',
 '197208122006041017',
 '196212051990111002',
 '196703281990011001',
 '197109191994011003',
 '197408151994031001',
 '196703061993032003',
 '196608061994121001',
 '196508211993032003',
 '199106032010101001',
 '197404301998112001',
 '197101231996032003',
 '197808182005021003',
 '198209132006041015',
 '196308251990011001',
 '197412161995101001',
 '196404131991021001',
 '196912262007011005',
 '197811181997111001',
 '196707181987092001',
 '196508151995031001',
 '196301011982031007',
 '197309231999031004',
 '196510251990031005',
 '196808241998031006',
 '196410111986031008',
 '196901011993031017',
 '196303311991031003',
 '196712291995032002',
 '196602141988031005',
 '196606211994021002',
 '198405012002121005',
 '196602151988031009',
 '197007231991011002',
 '196206161983031010',
 '196406111986031007',
 '197812122000031005',
 '196207181985031005',
 '196902271997031003',
 '196508081999011001',
 '197005231998031006',
 '197803272010011004',
 '196107151986031010',
 '196508121993031013',
 '196710241998031005',
 '197705262009011001',
 '196309121994031007',
 '196610071996031002',
 '198211122010011009',
 '197112111999022001',
 '196501271994031003',
 '198607142006022001',
 '197806052006041006',
 '196212181987031006',
 '198405242002122001',
 '196902011994032004',
 '196411201990021001',
 '198401162003121001',
 '196603251993031009',
 '196409291993031009',
 '197502202008012005',
 '196401201992031004',
 '197902182005011006',
 '197005151998031010',
 '196611021996031002',
 '198004192010011011',
 '196401111991031005',
 '196807071999031002',
 '196111051989031006',
 '197812202005011008',
 '196209201995031002',
 '198502082010011011',
 '196106141986031008',
 '197710062009011002',
 '196407241991031005',
 '197403312008011002',
 '196405171990021002',
 '198006152006041009',
 '196602212006041004',
 '197103122008011003',
 '196101261987021001',
 '197106242008011004',
 '196204251990031006',
 '197808032008011001',
 '196708282002121002',
 '197506152007011007',
 '196411021990121002',
 '197312191997032002',
 '196702051994031017',
 '197403102005022001',
 '196605191998031003',
 '197808222006042009',
 '196704171994021001',
 '197412122008011002',
 '197804082009021002',
 '197404242008011005',
 '196606061992031018',
 '196310041991031007',
 '197003202005011004',
 '196204191989031004',
 '197906092005012008',
 '197610092006041006',
 '198006192005011007',
 '197512271999031003',
 '196901211995032003',
 '198101252003121004',
 '196910211998031002',
 '196411161997031002',
 '196106261985032007',
 '197504082008011004',
 '197208181999031009',
 '197108121998031011',
 '198002042006041010',
 '196810181997031008',
 '197210192003121004',
 '197603072008011002',
 '197412032009011001',
 '196208191990031004',
 '196803291994031004',
 '196110231988031007',
 '196710061999011001',
 '198207312011011003',
 '196612051997031004',
 '196501071985031001',
 '197410051999011001',
 '196504261986032013',
 '196402181996031002',
 '197212272006041005',
 '196403061991032006',
 '197001281995121001',
 '198008062006041009',
 '196306021988031016',
 '196105241986031010',
 '196801241994031004',
 '196509131991032003',
 '196204241989032008',
 '198012182011011002',
 '196511171990112001',
 '196112261985012002',
 '198011032005012012',
 '196308111984111001',
 '198209172000121001',
 '196706011986121001',
 '196307021984011001',
 '198308172009021005',
 '196110181982031008',
 '198208102008011019',
 '197307201998032005',
 '196310311990101001',
 '197009252001121001',
 '196107101991081001',
 '196408152007011005',
 '196806242007011001',
 '196201181987032004',
 '196806021994032002',
 '196511301995031001',
 '198005202010011012',
 '196212071991032001',
 '197406231996031001',
 '196811261996011001',
 '196409041994011001',
 '197202152007011009',
 '197608252007011006',
 '196609041987021002',
 '197101181997031007',
 '196606061992031016',
 '198607292010011004',
 '196603231988032005',
 '197902132005011002',
 '197001152008012002',
 '196709031993032006',
 '196201021986031018',
 '196408061986031012',
 '196904251998031006',
 '196204181990032005',
 '196902211998031004',
 '196311271992032008',
 '197301122006042005',
 '196204211991031007',
 '197203112006041006',
 '196702211992031002',
 '196904101996031005',
 '196312161988022001',
 '197503072003122001',
 '196601091995031002',
 '196101111989091001',
 '197901012009011001',
 '196210151985031018',
 '197103281998031002',
 '198402052009021001',
 '197510082006041002',
 '198302202011012001',
 '196809241998032003',
 '196807231998032001',
 '196602241989021002',
 '198405272009011001',
 '198104282006041006',
 '197106091998031007',
 '196912031997032001',
 '198105172006041004',
 '196602281996031003',
 '198207212010011002',
 '196808091988031002',
 '196211181983031004',
 '197606162009011004',
 '196211271990031003',
 '197906162009011001',
 '196206021985031017',
 '196601301992031007',
 '197905042006041019',
 '196211271986031007',
 '196710011989031009',
 '196403111993031007',
 '196910151996032003',
 '196502121994031002',
 '196203041982021004',
 '198109022009021001',
 '196208031987011002',
 '196508311989031003',
 '197105132005011006',
 '195902071980121004',
 '197403291999032002',
 '196904101993031005',
 '197605032008012006',
 '196204021988031009',
 '196807081998031005',
 '196108151990031005',
 '197704021996031001',
 '197405281994031003',
 '196408121998031004',
 '198309222009011001',
 '196209081990031008',
 '196709252010011001',
 '198101262011011009',
 '196304171991031002',
 '197706111996031001',
 '196209241991021001',
 '196105281986031004',
 '197803061997031002',
 '196201211992031002',
 '197405222000031002',
 '196506221994031006',
 '196110141987091001',
 '197911212002121004',
 '195901011989021002',
 '196403031985031011',
 '196211291990032004',
 '197410091999031002',
 '196603311989031003',
 '198509012009021001',
 '196511091989031009',
 '197511182000031005',
 '195901311989021001',
 '197007171998031008',
 '197406191999021001',
 '197306161999031005',
 '196806241993031005',
 '196504081993031006',
 '197807202006041006',
 '196308141989031012',
 '196708061997032004',
 '196312011992032004',
 '197412022000031001',
 '196108241989031008',
 '197906061998101001',
 '196405161986031006',
 '197610132009011001',
 '196108171992031003',
 '197212142005011004',
 '198109282010011009',
 '196310091992031006',
 '197803211997111001',
 '197412081993032004',
 '198412152010011009',
 '196311151990021003',
 '196605201989031009',
 '197706262001122002',
 '196209271991031004',
 '196807071989031007',
 '196311061985031006',
 '196502081989031009',
 '197605032010011009',
 '198105081999121001',
 '198203182011011001',
 '198301252010011009',
 '197009151996032001',
 '197612142005011004',
 '196905191998032001',
 '196103291987031006',
 '197807252002122004',
 '196110151991031001',
 '196804041998032002',
 '196404201993031010',
 '197401141998032002',
 '196109091985032008',
 '197604021996021003',
 '198103272006042011',
 '198811042010101001',
 '196208161986032010',
 '197512272009011004',
 '196207211986031009',
 '197601042006041002',
 '197812221998031003',
 '196507171992091001',
 '196610161986031004',
 '198406272002121001',
 '197005261995032001',
 '196203071989031003',
 '197412092006041003',
 '196812131992031004',
 '197204272005011006',
 '197601232010011004',
 '197111191998031004',
 '197612152006041006',
 '198303192006042008',
 '196603251993031007',
 '198303242001121004',
 '196909221993071001',
 '198909282012061001',
 '196412101996031004',
 '198004011998101001',
 '196110041986031009',
 '196610201987081001',
 '197411302005011006',
 '197908041998031001',
 '198303242010121002',
 '199003032010102001',
 '199209132014061001',
 '197501122009011001',
 '197506281993111001',
 '196103101989031006',
 '197905012009021001',
 '196112041984111001',
 '196907071997021002',
 '198409142003121002',
 '196909081996031006',
 '197403182003121001',
 '197206241998031005',
 '197103221998032003',
 '196212241989031004',
 '198011072005012008',
 '197001091999032003',
 '196312121993031008',
 '197510172010011009',
 '198107232005012014',
 '196101261991031003',
 '197912222010011003',
 '196412081989032006',
 '196904161999031005',
 '196709181992032004',
 '198001141998102001',
 '196509061994031005',
 '196312181993032003',
 '197101032006042022',
 '198101181999122001',
 '196810082008011004',
 '197402142007012008',
 '196706121994011003',
 '197107151999022001',
 '197205221998032006',
 '197707172009012005',
 '198608062010012011',
 '196603011994032004',
 '196208231984031005',
 '198307312001121002',
 '197202061998031002',
 '197209131994031003',
 '197201221994032003',
 '198206202000121001',
 '198203182011012006',
 '196508191991031004',
 '197303132000032005',
 '197802201996122001',
 '197512102005012007',
 '197207121997032003',
 '196210271994031002',
 '197605232005011004',
 '196406021991031005',
 '197608031998031005',
 '197402121993032005',
 '196903231989031003',
 '196904162005021001',
 '196508191992031009',
 '197011012007011010',
 '198402132015032003',
 '197208281998031015',
 '197902112005011008',
 '198403012002122001',
 '196603151988031001',
 '197204031998031001',
 '197212141998031005',
 '196705211993031006',
 '197309161998032002',
 '197708092003121003',
 '196512091986111002',
 '196707241992021001',
 '197912142003121005',
 '197008291997031004',
 '197112291997031005',
 '196605171990021003',
 '196909211991031004',
 '197301191999021001',
 '196812301988031002',
 '198001212009022004',
 '198008132006042002',
 '198106052006042015',
 '198106252010011004',
 '197904292010012005',
 '197212242007012001',
 '198102152011011001',
 '196609021993122001',
 '197512092008012002',
 '196803081988021001',
 '197107051998032006',
 '198305022010012011',
 '197507242010011007',
 '196508101996032002',
 '198709242007012001',
 '197401121998031005',
 '198005151998102002',
 '197001231999031005',
 '197105061998031003',
 '197406172008011005',
 '197608252005011008',
 '196703061995031001',
 '197208042000031005',
 '196703261991031006',
 '197903102008012005',
 '196904061991021001',
 '198105052010011022',
 '196911201993031006',
 '196703051994032004',
 '197311202000031004',
 '197011202008011003']

In [ ]:
# Combine three lists into one
all_nips = pd.unique(list(nip_ketuas) + list(nip_jpts_list) + list(nips)).tolist()

all_nips

['197306121998032013',
 '197807302006042005',
 '197701142009011001',
 '198007152011012001',
 '197909122011012001',
 '197908122006042006',
 '197309121998031004',
 '198008112010011002',
 '198011142011012003',
 '197306282008011003',
 '196903172002121001',
 '196806141997031004',
 '198201122001121004',
 '198001262011011002',
 '199208142014061001',
 '197902212008012003',
 '197603112014122001',
 '198010202010011003',
 '197103022005011010',
 '198211132008082001',
 '197606162008011004',
 '197011251998031005',
 '198609202010012006',
 '197504281999022001',
 '197902162011011001',
 '197410032008012003',
 '198007042011011001',
 '197411241999031005',
 '196902261989031004',
 '197402152006041009',
 '197409032009011001',
 '197108101997022005',
 '197005231998031007',
 '197608162005011011',
 '197904102011011002',
 '196705171990111001',
 '197410262008012003',
 '197601242006042004',
 '198108232005011008',
 '197709022009012001',
 '199709232020121009',
 '197606162009011004',
 '197707282005011006',
 '198209042009011001',
 '198611062004122002',
 '198702232011012002',
 '197810212011012002',
 '197109281999032008',
 '196903102007011010',
 '196906291991021001',
 '199705302020121011',
 '197311052003122004',
 '198008042010012003',
 '199803142022031014',
 '199003032020122012',
 '198006132010011008',
 '199105252014021002',
 '199408152020122021',
 '197910272008012003',
 '197106281998031007',
 '196710311990032004',
 '197002052008012009',
 '196702181996032001',
 '196810191999012001',
 '198106282003122002',
 '197008041998032002',
 '197210061998032005',
 '196711062000031003',
 '197403241999032002',
 '197108151998032010',
 '197311172007011006',
 '197904302008011002',
 '198404192010011009',
 '196811081998032002',
 '197902132010011001',
 '198004122011012001',
 '197607152007012010',
 '197206012007011003',
 '199306152017081001',
 '198710052015032006',
 '198102032010012002',
 '197307042007011005',
 '197810081998031003',
 '197306032008011005',
 '197906202008011004',
 '197001011994031014',
 '198306232006042011',
 '199405162017081003',
 '198308272010121002',
 '199111042014021002',
 '198503282011011003',
 '196903241999011001',
 '198406052010012014',
 '199508302017081002',
 '198512172010012008',
 '197512262005011002',
 '198112112010012008',
 '198405242015031006',
 '197811252010011009',
 '197303081998032008',
 '199207282015071002',
 '197101241997022003',
 '197003091991031007',
 '198203052009022002',
 '198603152010011002',
 '198905082020121009',
 '198509302010012003',
 '197602242006041006',
 '197606072009032002',
 '197206251999032002',
 '197810012011012009',
 '196702221993031007',
 '198211072011012005',
 '198604172011011005',
 '198611032011011002',
 '199711132019082001',
 '198908172015031003',
 '200007012022021001',
 '197105012005011006',
 '197207152005012001',
 '198112072010011002',
 '197701032009011005',
 '199303202015071002',
 '199408222016091001',
 '199604152022031010',
 '197312221999032005',
 '197607292007012007',
 '198604302007012001',
 '198608202010011007',
 '198903102015032004',
 '197607102014121002',
 '199201172020122016',
 '196812091988032003',
 '199107092012062001',
 '198003032001122002',
 '197507132000031004',
 '198205172010012001',
 '199206072020122015',
 '198501122020122005',
 '197702031999012001',
 '196810031994031006',
 '196902032007012007',
 '197208111994042001',
 '196812161992031004',
 '198811092020121005',
 '196909031994032001',
 '196612051993032002',
 '197105262000032004',
 '196908092007012007',
 '197104222007012003',
 '196707041992022002',
 '197108022008011002',
 '198701132010011003',
 '197911232010012005',
 '196805271994032006',
 '197506121998031004',
 '196806121990092002',
 '197409132008011003',
 '196910221998031003',
 '198801272020122003',
 '197611252009021001',
 '198010022006042015',
 '197603042010012002',
 '199505252020122036',
 '197608142008011002',
 '197510172008011002',
 '198601102010012015',
 '198707242010012004',
 '197501142009012004',
 '197912242010011002',
 '197608102006042023',
 '197607022011011003',
 '198404232010011012',
 '199308022020122017',
 '197510232009012001',
 '197907261998101001',
 '197312292008011003',
 '198312312010011024',
 '199403132020122020',
 '197409102008011005',
 '197010162007011006',
 '196911302008011002',
 '197201271999011001',
 '197203191997031003',
 '199011092012061001',
 '196809241993102001',
 '198111252010012007',
 '198004282009011002',
 '197709072008011006',
 '196902121994011001',
 '198010262000031002',
 '198911242011011001',
 '197405192009011002',
 '196711241996032002',
 '196912252005011009',
 '196606031996031002',
 '197001122009012001',
 '199704042019031001',
 '197509272006042005',
 '197309302014122001',
 '197101202005011008',
 '197403101998031005',
 '198205042010011010',
 '199412302020122021',
 '198407142009021001',
 '198707232011011003',
 '197806232005012001',
 '199407202020121005',
 '197503012007011007',
 '197107081998032004',
 '199706112022031011',
 '198310292010011002',
 '196906021998031004',
 '196712151994031010',
 '199604052020121006',
 '196712051993031009',
 '197412062007011008',
 '196905041998032007',
 '198902012011012005',
 '198202032006042008',
 '197204092009011001',
 '196902281999031002',
 '196609112008011001',
 '196703221997032001',
 '197408291994031006',
 '196905231994032005',
 '197309221999032004',
 '199110112015071001',
 '197605031998031003',
 '199711252020122010',
 '198005122010011012',
 '198801082015031004',
 '197805081997031001',
 '198210232005011004',
 '196902261993031003',
 '197206062006042008',
 '197411101994031008',
 '198011202008011005',
 '198603202011012003',
 '197307272008011005',
 '198108202000031002',
 '197102112014122001',
 '197002062001121002',
 '197004202003121003',
 '197612131997031005',
 '196906211991031001',
 '197412052000121002',
 '197410091995031001',
 '197407132006041004',
 '197212142006041003',
 '198709092020121007',
 '197208291999011001',
 '198712302015031003',
 '197401092010011003',
 '198508292020122004',
 '198201022010011014',
 '198411162009021001',
 '197311202005011005',
 '199011162015071001',
 '197112242009011001',
 '197412232009011001',
 '197612012014071001',
 '198303282011012003',
 '197405021994031002',
 '198404282011011006',
 '198510262010012008',
 '198608232015031003',
 '197104011998031010',
 '197005141998031004',
 '198309042015031001',
 '198309182011011001',
 '198808302011011003',
 '197705172009011001',
 '198107192010011009',
 '198301142010011014',
 '198207122005012016',
 '196906201998031003',
 '198010112005012001',
 '197812112005012001',
 '197403012008121001',
 '197812082009011003',
 '197609302005012006',
 '197107101998032007',
 '197608102011011003',
 '198604082009022005',
 '199105022020121008',
 '196701301998031002',
 '198010192008011002',
 '197602272009011002',
 '196905301992031007',
 '198101312011011001',
 '197108202008011004',
 '197508042007011005',
 '197204212008011003',
 '197002111992031008',
 '197111121998032003',
 '199404082020122028',
 '199202132020122019',
 '197102032005011009',
 '197204122007012004',
 '198310032011011003',
 '197105252002121007',
 '197907282009011001',
 '197008101992031010',
 '197710242006041006',
 '198912292020122011',
 '197007041998031002',
 '197412232009022003',
 '197506051996031002',
 '198704292015031003',
 '198201192009022001',
 '199403182020122016',
 '198701222020122009',
 '197007292008011004',
 '197102211996032002',
 '199608192020121009',
 '199403232020122016',
 '197108091998031003',
 '197608152010011004',
 '197901012009022003',
 '198006221999031001',
 '197709132009011001',
 '197410192000031003',
 '198010192010012007',
 '198409042011012005',
 '197804142008011003',
 '197006232000031002',
 '197504272008012006',
 '197611112014121003',
 '197403312008011002',
 '198508032010011008',
 '198103092006042013',
 '197408101996031003',
 '197911102009011001',
 '197903072009011007',
 '197708072009021001',
 '197807162009021003',
 '197102031997031006',
 '196810131999031003',
 '198310282009021003',
 '197401102008011005',
 '198309042005011001',
 '197909111998031002',
 '197405192006041004',
 '197211172006041007',
 '197705132009011002',
 '196811041999031003',
 '197305062006041013',
 '197210202008011003',
 '198509072010011012',
 '197106021998031006',
 '197011042007012006',
 '197804262009021001',
 '197305072008011001',
 '198004212009022001',
 '198111262011011001',
 '199203072020121012',
 '197402142005012006',
 '198109262005012017',
 '198103192014121001',
 '197610282009011004',
 '197606062008011006',
 '199404152019031008',
 '197212012010011001',
 '197108032006041013',
 '197010221990031001',
 '197108021998031006',
 '199406032016091002',
 '198006292010011008',
 '198206302009121001',
 '199501272017082001',
 '198407182010012020',
 '197911242014112001',
 '197308192002122001',
 '198107022009012002',
 '196808112002121008',
 '197512232010012001',
 '197408222006042013',
 '197709272008011003',
 '197707282008011004',
 '197210142005021002',
 '197003111997031004',
 '197008242002121001',
 '197812292009011002',
 '197606042008011003',
 '199701152018081001',
 '197902022010011007',
 '197609091996031004',
 '197908222000031001',
 '196912141991031004',
 '198403052015032004',
 '198308052011011004',
 '197304181997031004',
 '198711072015031002',
 '197605232006041006',
 '198206062010011013',
 '197203212006041001',
 '197903222002121002',
 '196906151994031017',
 '196904101998031008',
 '197306271994031003',
 '199112162012061001',
 '197312051996021002',
 '197601022003122006',
 '199404022020121012',
 '197604042005012009',
 '199110292015031003',
 '198804292011012003',
 '197303202006042004',
 '196904091998031007',
 '196807071990031008',
 '197503152008011004',
 '197502271998031002',
 '197002062008011004',
 '197012111996031003',
 '198211072010011002',
 '198103252011012004',
 '197607041997031002',
 '198109022015032001',
 '197610012005011010',
 '199511162017081001',
 '197807262008011004',
 '197308081999032005',
 '197905022005012012',
 '198208112015032002',
 '198303142009021002',
 '198608212010012008',
 '197308122006041006',
 '197308271998032003',
 '197509071999012001',
 '197601012008011005',
 '199405062020121011',
 '199409102020121008',
 '197501172009011001',
 '197411282009011002',
 '197412022009022001',
 '199510292020121006',
 '196906291999011001',
 '197506272003122001',
 '197009071995032002',
 '196802221994031009',
 '197203301999031002',
 '197211071999011001',
 '197102062008011003',
 '196907152008011005',
 '197503042010011003',
 '198404152003121001',
 '197410221998031005',
 '197802032009011004',
 '196911222007011007',
 '197802202010011001',
 '197204071996031002',
 '197506252008012003',
 '198103222008011003',
 '197112131994031001',
 '197405091998032002',
 '196808051999031003',
 '197307312009011001',
 '197212231998032006',
 '198203112001122001',
 '198507202011011004',
 '197201161999012001',
 '197204031999021001',
 '196906221998031007',
 '197107041998032005',
 '198501022010012018',
 '197809072009012001',
 '197705182010011012',
 '197501282009022004',
 '197905082008011012',
 '198004162006041006',
 '198103102009022002',
 '197501071998111001',
 '198110262009011001',
 '197805152009011003',
 '197607172009011004',
 '197901242010011004',
 '198604172011011007',
 '199212302022032006',
 '196909051999011001',
 '197511101998031003',
 '196907191995032004',
 '196907272008012010',
 '196901031993032009',
 '197706301998031002',
 '197307151998032005',
 '197703212009011003',
 '197302192009012002',
 '198111152009021001',
 '197011071998031007',
 '198406182010011007',
 '197603062007011008',
 '197202102002121003',
 '196907251994032007',
 '197112301992031002',
 '197708261999032002',
 '197310092008011003',
 '196812031989031008',
 '198005122010011004',
 '198409262011011003',
 '199401122016091001',
 '198105242010012009',
 '198003172000031003',
 '197703091998031003',
 '199305072020122024',
 '196904062008011003',
 '197908062008011002',
 '196810201991031007',
 '199011022022032005',
 '197111271998031004',
 '199409082020121008',
 '197103161998031006',
 '198604142010011007',
 '199203042023211011',
 '198409032011011001',
 '197604232009022002',
 '199608072022031018',
 '197508171996031003',
 '197810262010011003',
 '199406062020122035',
 '197606012003121003',
 '198103202011012002',
 '199201192022031006',
 '199108032020121014',
 '198204192010011011',
 '199403262017081001',
 '199408222016091002',
 '198411212011011001',
 '196901151998031005',
 '196910151994031006',
 '197507211998032003',
 '196910121993022003',
 '197110081997032006',
 '197702282000032003',
 '196912092005012001',
 '197306052005011013',
 '197208041998031008',
 '197901232010011001',
 '197106012006041004',
 '197312101994032005',
 '197001221996032002',
 '197209281995011001',
 '199606042020122019',
 '199611032019082001',
 '198104132009021004',
 '199105132020121017',
 '197403052007011010',
 '199011152020122020',
 '198106212011011002',
 '198310272009011005',
 '198201262010011004',
 '197412062014121001',
 '197409062014122001',
 '196706101991021002',
 '196708271990031008',
 '198306112011011002',
 '198910222020121003',
 '198108242006041001',
 '198808212022032006',
 '197412182008011004',
 '196812231988032002',
 '199812082022031005',
 '199006112022031004',
 '198911222022031003',
 '197402062008012010',
 '197403112008011001',
 '196807191993032005',
 '197302142008011002',
 '198909162015031004',
 '196812011998031006',
 '196908171996031010',
 '197703262006042009',
 '197512072010011003',
 '197402231993031001',
 '198304082009022008',
 '199001122015032007',
 '197408032005011001',
 '198711292010012008',
 '197007131997032002',
 '197506162007011007',
 '198012202010011014',
 '197905232010011006',
 '198006172009021002',
 '196812221998031006',
 '196704091989032005',
 '197005121997031008',
 '196908151996031002',
 '196807051992031008',
 '197605292006042008',
 '196710141998032002',
 '197803032010011008',
 '196709161988021002',
 '197302221995101001',
 '197107131999032003',
 '196812031998031005',
 '197209061998031004',
 '197412302000032005',
 '197006161998031006',
 '199512272020122015',
 '197009041998032006',
 '197108021998031008',
 '196710151998031003',
 '197112261998031009',
 '197006241998031008',
 '197003051998031006',
 '197307281994031001',
 '197107062006041004',
 '196702151998032003',
 '196802181998031006',
 '196909111998031006',
 '196909131998032007',
 '196905101998031009',
 '197001241998031004',
 '197207142000032005',
 '196912271998031008',
 '196811251998031005',
 '196904261998031006',
 '196809272007011004',
 '196704151998031007',
 '196803301998031004',
 '196804171998031007',
 '196911141998031006',
 '196709291998031007',
 '196612041998031006',
 '196802091998031005',
 '196911111998031010',
 '197208171998031007',
 '196710201998031005',
 '197105031998031008',
 '197511242009021002',
 '199208222014062001',
 '196801161992032006',
 '197310171998031004',
 '199112262015032003',
 '199608192022032018',
 '196804072000031003',
 '197111131998031003',
 '197006231998032006',
 '199007082015031001',
 '196904061998031004',
 '197203051998031007',
 '197506132000032009',
 '196711051998031002',
 '196709121998031006',
 '196906111998032001',
 '197010251998031010',
 '198010142007012003',
 '197006191998031007',
 '196703131998031008',
 '197905032005011009',
 '197210011998032005',
 '198911102020121011',
 '198008021998101001',
 '198610032010011012',
 '199301112016091002',
 '199310102020121014',
 '198411282011011002',
 '199009222020122017',
 '197408282006041011',
 '197108131998031005',
 '197401102006041003',
 '198512272014021001',
 '199305252020121013',
 '197802122009012002',
 '198707072014021002',
 '197004281997032004',
 '198705022020121006',
 '197205252006041004',
 '199602032019082001',
 '197312021999032003',
 '198304032011011003',
 '199107082020121006',
 '197204232014121003',
 '197001182006042006',
 '198711152011011002',
 '199610102020121008',
 '197107102007011010',
 '197805282008011004',
 '197709182014111001',
 '199103172020121015',
 '199306182020122014',
 '198505312011011005',
 '197810042005011007',
 '197106282008011002',
 '198101082011011002',
 '198007062007012011',
 '198001242003121003',
 '199408212016092001',
 '196808291989032002',
 '196609081994031005',
 '197311062014121001',
 '197805072007011008',
 '197008022007011014',
 '197508032009011002',
 '198011182011011001',
 '198306032002121001',
 '197811132009011004',
 '199505272020121023',
 '197611142008011004',
 '197811222010012001',
 '198612202020121005',
 '198007042010011002',
 '198603182010012009',
 '197812302009011001',
 '199112122015071003',
 '198105122014121001',
 '198002172006041005',
 '197908112014111001',
 '198007022009021001',
 '199508062022031007',
 '199512192018081002',
 '200009032022021001',
 '200002072022021001',
 '197304072008011003',
 '198501012011011004',
 '197908012014102001',
 '198012182015032001',
 '198201302009011003',
 '197805242008012009',
 '197109012007011004',
 '197603022002122006',
 '198601052015031003',
 '197208262007011004',
 '197701101996122001',
 '199211122020121014',
 '197601292009021001',
 '198909052019031005',
 '199612142020121010',
 '199210112015031003',
 '197312122005011010',
 '197208212005012006',
 '198303252015031002',
 '199209012020121011',
 '197808082008012015',
 '197907102008012036',
 '197310222000032001',
 '197105191993111001',
 '196706261994032006',
 '200009102022021001',
 '199106072014062001',
 '196902042008011001',
 '197212292008012002',
 '197808172010012002',
 '198309212010012005',
 '197504071999032002',
 '197803192007012008',
 '198610232011011002',
 '197203311998032003',
 '198207062009012001',
 '197811142008012003',
 '198102082009021003',
 '197502202008012005',
 '198801092020122009',
 '199505072020122017',
 '197710022006042011',
 '198904272014032001',
 '197806062005011008',
 '197910132014091002',
 '198508192010011007',
 '197107171993031007',
 '199612272020122013',
 '196712131992031005',
 '197204152000121003',
 '197111201998021002',
 '198503022009021002',
 '198302172006042011',
 '198011202008012001',
 '197407032005012008',
 '197510102008011005',
 '199409052016091001',
 '198006302009012001',
 '198108032014072001',
 '197606132010012002',
 '197606282008012004',
 '198110062009012002',
 '198005242010011004',
 '196904031992081001',
 '198912122015021001',
 '199003102020122010',
 '198706012010121001',
 '198006242023211002',
 '197609072009021003',
 '197610062011011001',
 '197505102006042007',
 '197012131992032006',
 '198508242011011002',
 '199305092015072002',
 '198708252011012003',
 '196901082007012003',
 '197510152014122001',
 '197101312007012002',
 '198807222020121006',
 '198101042011012002',
 '198702182011011001',
 '198110312011012001',
 '198010042009022001',
 '197008242007012005',
 '197802132008012005',
 '198901102020122007',
 '198710192011011001',
 '199311082019032014',
 '197809022010012001',
 '197606202006042007',
 '197704122009011003',
 '197409102010012003',
 '198110142014121003',
 '197507072006041013',
 '198403142011011001',
 '197109081998032004',
 '197706062010011001',
 '197007161993032005',
 '198106112010012014',
 '199705262020122014',
 '197002251992121001',
 '199611182020121005',
 '196608061993031004',
 '199204112014061001',
 '197906192010011008',
 '196910051989032004',
 '199701242022032021',
 '197808182014092001',
 '198108112014121001',
 '199408012020121016',
 '198603222011012005',
 '198104072011011001',
 '197311092007011005',
 '197904292010012005',
 '196909112007011007',
 '199407022020122016',
 '196906141997021003',
 '197906202005011002',
 '198607172015031002',
 '197212312008011017',
 '197612102006042005',
 '199207152020121017',
 '196811271990031003',
 '199705302020121009',
 '198204112008012004',
 '197502122007011006',
 '199810112022032013',
 '198411232009121002',
 '197010132008012006',
 '196508181993031001',
 '197310152006041011',
 '197902032008011004',
 '198008172009011002',
 '197303021992032002',
 '199009142014021002',
 '196909191999012001',
 '199404172020122018',
 '198101152009021002',
 '199410172020121010',
 '196712011992111001',
 '196901081994031003',
 '196901091991032009',
 '197512162006041002',
 '198204052010011002',
 '198703202015031006',
 '197003071993032002',
 '197911262011012002',
 '199311222015071001',
 '199109072020121010',
 '197208182014122005',
 '199510092020121011',
 '198903072012061001',
 '196807121991032006',
 '197405251999032016',
 '198303172009122001',
 '197210051993031006',

In [69]:
# Make single string separated by comma
nip_all_str = ','.join(all_nips)

nip_all_str

'197306121998032013,197807302006042005,197701142009011001,198007152011012001,197909122011012001,197908122006042006,197309121998031004,198008112010011002,198011142011012003,197306282008011003,196903172002121001,196806141997031004,198201122001121004,198001262011011002,199208142014061001,197902212008012003,197603112014122001,198010202010011003,197103022005011010,198211132008082001,197606162008011004,197011251998031005,198609202010012006,197504281999022001,197902162011011001,197410032008012003,198007042011011001,197411241999031005,196902261989031004,197402152006041009,197409032009011001,197108101997022005,197005231998031007,197608162005011011,197904102011011002,196705171990111001,197410262008012003,197601242006042004,198108232005011008,197709022009012001,199709232020121009,197606162009011004,197707282005011006,198209042009011001,198611062004122002,198702232011012002,197810212011012002,197109281999032008,196903102007011010,196906291991021001,199705302020121011,197311052003122004,198008042010012003,199803142022031014,199003032020122012,198006132010011008,199105252014021002,199408152020122021,197910272008012003,197106281998031007,196710311990032004,197002052008012009,196702181996032001,196810191999012001,198106282003122002,197008041998032002,197210061998032005,196711062000031003,197403241999032002,197108151998032010,197311172007011006,197904302008011002,198404192010011009,196811081998032002,197902132010011001,198004122011012001,197607152007012010,197206012007011003,199306152017081001,198710052015032006,198102032010012002,197307042007011005,197810081998031003,197306032008011005,197906202008011004,197001011994031014,198306232006042011,199405162017081003,198308272010121002,199111042014021002,198503282011011003,196903241999011001,198406052010012014,199508302017081002,198512172010012008,197512262005011002,198112112010012008,198405242015031006,197811252010011009,197303081998032008,199207282015071002,197101241997022003,197003091991031007,198203052009022002,198603152010011002,198905082020121009,198509302010012003,197602242006041006,197606072009032002,197206251999032002,197810012011012009,196702221993031007,198211072011012005,198604172011011005,198611032011011002,199711132019082001,198908172015031003,200007012022021001,197105012005011006,197207152005012001,198112072010011002,197701032009011005,199303202015071002,199408222016091001,199604152022031010,197312221999032005,197607292007012007,198604302007012001,198608202010011007,198903102015032004,197607102014121002,199201172020122016,196812091988032003,199107092012062001,198003032001122002,197507132000031004,198205172010012001,199206072020122015,198501122020122005,197702031999012001,196810031994031006,196902032007012007,197208111994042001,196812161992031004,198811092020121005,196909031994032001,196612051993032002,197105262000032004,196908092007012007,197104222007012003,196707041992022002,197108022008011002,198701132010011003,197911232010012005,196805271994032006,197506121998031004,196806121990092002,197409132008011003,196910221998031003,198801272020122003,197611252009021001,198010022006042015,197603042010012002,199505252020122036,197608142008011002,197510172008011002,198601102010012015,198707242010012004,197501142009012004,197912242010011002,197608102006042023,197607022011011003,198404232010011012,199308022020122017,197510232009012001,197907261998101001,197312292008011003,198312312010011024,199403132020122020,197409102008011005,197010162007011006,196911302008011002,197201271999011001,197203191997031003,199011092012061001,196809241993102001,198111252010012007,198004282009011002,197709072008011006,196902121994011001,198010262000031002,198911242011011001,197405192009011002,196711241996032002,196912252005011009,196606031996031002,197001122009012001,199704042019031001,197509272006042005,197309302014122001,197101202005011008,197403101998031005,198205042010011010,199412302020122021,198407142009021001,198707232011011003,197806232005012001,199407202020121005,197503012007011007,197107081998032004,199706112022031011,198310292010011002,196906021998031004,196712151994031010,199604052020121006,196712051993031009,197412062007011008,196905041998032007,198902012011012005,198202032006042008,197204092009011001,196902281999031002,196609112008011001,196703221997032001,197408291994031006,196905231994032005,197309221999032004,199110112015071001,197605031998031003,199711252020122010,198005122010011012,198801082015031004,197805081997031001,198210232005011004,196902261993031003,197206062006042008,197411101994031008,198011202008011005,198603202011012003,197307272008011005,198108202000031002,197102112014122001,197002062001121002,197004202003121003,197612131997031005,196906211991031001,197412052000121002,197410091995031001,197407132006041004,197212142006041003,198709092020121007,197208291999011001,198712302015031003,197401092010011003,198508292020122004,198201022010011014,198411162009021001,197311202005011005,199011162015071001,197112242009011001,197412232009011001,197612012014071001,198303282011012003,197405021994031002,198404282011011006,198510262010012008,198608232015031003,197104011998031010,197005141998031004,198309042015031001,198309182011011001,198808302011011003,197705172009011001,198107192010011009,198301142010011014,198207122005012016,196906201998031003,198010112005012001,197812112005012001,197403012008121001,197812082009011003,197609302005012006,197107101998032007,197608102011011003,198604082009022005,199105022020121008,196701301998031002,198010192008011002,197602272009011002,196905301992031007,198101312011011001,197108202008011004,197508042007011005,197204212008011003,197002111992031008,197111121998032003,199404082020122028,199202132020122019,197102032005011009,197204122007012004,198310032011011003,197105252002121007,197907282009011001,197008101992031010,197710242006041006,198912292020122011,197007041998031002,197412232009022003,197506051996031002,198704292015031003,198201192009022001,199403182020122016,198701222020122009,197007292008011004,197102211996032002,199608192020121009,199403232020122016,197108091998031003,197608152010011004,197901012009022003,198006221999031001,197709132009011001,197410192000031003,198010192010012007,198409042011012005,197804142008011003,197006232000031002,197504272008012006,197611112014121003,197403312008011002,198508032010011008,198103092006042013,197408101996031003,197911102009011001,197903072009011007,197708072009021001,197807162009021003,197102031997031006,196810131999031003,198310282009021003,197401102008011005,198309042005011001,197909111998031002,197405192006041004,197211172006041007,197705132009011002,196811041999031003,197305062006041013,197210202008011003,198509072010011012,197106021998031006,197011042007012006,197804262009021001,197305072008011001,198004212009022001,198111262011011001,199203072020121012,197402142005012006,198109262005012017,198103192014121001,197610282009011004,197606062008011006,199404152019031008,197212012010011001,197108032006041013,197010221990031001,197108021998031006,199406032016091002,198006292010011008,198206302009121001,199501272017082001,198407182010012020,197911242014112001,197308192002122001,198107022009012002,196808112002121008,197512232010012001,197408222006042013,197709272008011003,197707282008011004,197210142005021002,197003111997031004,197008242002121001,197812292009011002,197606042008011003,199701152018081001,197902022010011007,197609091996031004,197908222000031001,196912141991031004,198403052015032004,198308052011011004,197304181997031004,198711072015031002,197605232006041006,198206062010011013,197203212006041001,197903222002121002,196906151994031017,196904101998031008,197306271994031003,199112162012061001,197312051996021002,197601022003122006,199404022020121012,197604042005012009,199110292015031003,198804292011012003,197303202006042004,196904091998031007,196807071990031008,197503152008011004,197502271998031002,197002062008011004,197012111996031003,198211072010011002,198103252011012004,197607041997031002,198109022015032001,197610012005011010,199511162017081001,197807262008011004,197308081999032005,197905022005012012,198208112015032002,198303142009021002,198608212010012008,197308122006041006,197308271998032003,197509071999012001,197601012008011005,199405062020121011,199409102020121008,197501172009011001,197411282009011002,197412022009022001,199510292020121006,196906291999011001,197506272003122001,197009071995032002,196802221994031009,197203301999031002,197211071999011001,197102062008011003,196907152008011005,197503042010011003,198404152003121001,197410221998031005,197802032009011004,196911222007011007,197802202010011001,197204071996031002,197506252008012003,198103222008011003,197112131994031001,197405091998032002,196808051999031003,197307312009011001,197212231998032006,198203112001122001,198507202011011004,197201161999012001,197204031999021001,196906221998031007,197107041998032005,198501022010012018,197809072009012001,197705182010011012,197501282009022004,197905082008011012,198004162006041006,198103102009022002,197501071998111001,198110262009011001,197805152009011003,197607172009011004,197901242010011004,198604172011011007,199212302022032006,196909051999011001,197511101998031003,196907191995032004,196907272008012010,196901031993032009,197706301998031002,197307151998032005,197703212009011003,197302192009012002,198111152009021001,197011071998031007,198406182010011007,197603062007011008,197202102002121003,196907251994032007,197112301992031002,197708261999032002,197310092008011003,196812031989031008,198005122010011004,198409262011011003,199401122016091001,198105242010012009,198003172000031003,197703091998031003,199305072020122024,196904062008011003,197908062008011002,196810201991031007,199011022022032005,197111271998031004,199409082020121008,197103161998031006,198604142010011007,199203042023211011,198409032011011001,197604232009022002,199608072022031018,197508171996031003,197810262010011003,199406062020122035,197606012003121003,198103202011012002,199201192022031006,199108032020121014,198204192010011011,199403262017081001,199408222016091002,198411212011011001,196901151998031005,196910151994031006,197507211998032003,196910121993022003,197110081997032006,197702282000032003,196912092005012001,197306052005011013,197208041998031008,197901232010011001,197106012006041004,197312101994032005,197001221996032002,197209281995011001,199606042020122019,199611032019082001,198104132009021004,199105132020121017,197403052007011010,199011152020122020,198106212011011002,198310272009011005,198201262010011004,197412062014121001,197409062014122001,196706101991021002,196708271990031008,198306112011011002,198910222020121003,198108242006041001,198808212022032006,197412182008011004,196812231988032002,199812082022031005,199006112022031004,198911222022031003,197402062008012010,197403112008011001,196807191993032005,197302142008011002,198909162015031004,196812011998031006,196908171996031010,197703262006042009,197512072010011003,197402231993031001,198304082009022008,199001122015032007,197408032005011001,198711292010012008,197007131997032002,197506162007011007,198012202010011014,197905232010011006,198006172009021002,196812221998031006,196704091989032005,197005121997031008,196908151996031002,196807051992031008,197605292006042008,196710141998032002,197803032010011008,196709161988021002,197302221995101001,197107131999032003,196812031998031005,197209061998031004,197412302000032005,197006161998031006,199512272020122015,197009041998032006,197108021998031008,196710151998031003,197112261998031009,197006241998031008,197003051998031006,197307281994031001,197107062006041004,196702151998032003,196802181998031006,196909111998031006,196909131998032007,196905101998031009,197001241998031004,197207142000032005,196912271998031008,196811251998031005,196904261998031006,196809272007011004,196704151998031007,196803301998031004,196804171998031007,196911141998031006,196709291998031007,196612041998031006,196802091998031005,196911111998031010,197208171998031007,196710201998031005,197105031998031008,197511242009021002,199208222014062001,196801161992032006,197310171998031004,199112262015032003,199608192022032018,196804072000031003,197111131998031003,197006231998032006,199007082015031001,196904061998031004,197203051998031007,197506132000032009,196711051998031002,196709121998031006,196906111998032001,197010251998031010,198010142007012003,197006191998031007,196703131998031008,197905032005011009,197210011998032005,198911102020121011,198008021998101001,198610032010011012,199301112016091002,199310102020121014,198411282011011002,199009222020122017,197408282006041011,197108131998031005,197401102006041003,198512272014021001,199305252020121013,197802122009012002,198707072014021002,197004281997032004,198705022020121006,197205252006041004,199602032019082001,197312021999032003,198304032011011003,199107082020121006,197204232014121003,197001182006042006,198711152011011002,199610102020121008,197107102007011010,197805282008011004,197709182014111001,199103172020121015,199306182020122014,198505312011011005,197810042005011007,197106282008011002,198101082011011002,198007062007012011,198001242003121003,199408212016092001,196808291989032002,196609081994031005,197311062014121001,197805072007011008,197008022007011014,197508032009011002,198011182011011001,198306032002121001,197811132009011004,199505272020121023,197611142008011004,197811222010012001,198612202020121005,198007042010011002,198603182010012009,197812302009011001,199112122015071003,198105122014121001,198002172006041005,197908112014111001,198007022009021001,199508062022031007,199512192018081002,200009032022021001,200002072022021001,197304072008011003,198501012011011004,197908012014102001,198012182015032001,198201302009011003,197805242008012009,197109012007011004,197603022002122006,198601052015031003,197208262007011004,197701101996122001,199211122020121014,197601292009021001,198909052019031005,199612142020121010,199210112015031003,197312122005011010,197208212005012006,198303252015031002,199209012020121011,197808082008012015,197907102008012036,197310222000032001,197105191993111001,196706261994032006,200009102022021001,199106072014062001,196902042008011001,197212292008012002,197808172010012002,198309212010012005,197504071999032002,197803192007012008,198610232011011002,197203311998032003,198207062009012001,197811142008012003,198102082009021003,197502202008012005,198801092020122009,199505072020122017,197710022006042011,198904272014032001,197806062005011008,197910132014091002,198508192010011007,197107171993031007,199612272020122013,196712131992031005,197204152000121003,197111201998021002,198503022009021002,198302172006042011,198011202008012001,197407032005012008,197510102008011005,199409052016091001,198006302009012001,198108032014072001,197606132010012002,197606282008012004,198110062009012002,198005242010011004,196904031992081001,198912122015021001,199003102020122010,198706012010121001,198006242023211002,197609072009021003,197610062011011001,197505102006042007,197012131992032006,198508242011011002,199305092015072002,198708252011012003,196901082007012003,197510152014122001,197101312007012002,198807222020121006,198101042011012002,198702182011011001,198110312011012001,198010042009022001,197008242007012005,197802132008012005,198901102020122007,198710192011011001,199311082019032014,197809022010012001,197606202006042007,197704122009011003,197409102010012003,198110142014121003,197507072006041013,198403142011011001,197109081998032004,197706062010011001,197007161993032005,198106112010012014,199705262020122014,197002251992121001,199611182020121005,196608061993031004,199204112014061001,197906192010011008,196910051989032004,199701242022032021,197808182014092001,198108112014121001,199408012020121016,198603222011012005,198104072011011001,197311092007011005,197904292010012005,196909112007011007,199407022020122016,196906141997021003,197906202005011002,198607172015031002,197212312008011017,197612102006042005,199207152020121017,196811271990031003,199705302020121009,198204112008012004,197502122007011006,199810112022032013,198411232009121002,197010132008012006,196508181993031001,197310152006041011,197902032008011004,198008172009011002,197303021992032002,199009142014021002,196909191999012001,199404172020122018,198101152009021002,199410172020121010,196712011992111001,196901081994031003,196901091991032009,197512162006041002,198204052010011002,198703202015031006,197003071993032002,197911262011012002,199311222015071001,199109072020121010,197208182014122005,199510092020121011,198903072012061001,196807121991032006,197405251999032016,198303172009122001,197210051993031006,197010232000031003,197210201999031008,197305191994032004,197201031993032007,197109122008011003,198701022019032008,197210222014061002,197305101993122001,199202092020121007,199307292020122020,196911162007012007,197606232010011009,197612312008011004,197609212010011006,197207101998031008,196910022000031006,196803061998031006,197408072008011002,196902121997021006,198007052001122006,198901282020122009,199107262020122005,198104202006042010,198807152010011001,198010072014122001,198403072009022002,197607092009011001,198207112005011004,198103112005011005,197410102008011002,198209052006042009,197911282010012004,197909222009012001,197911152014072002,197406022009012001,198011172000032001,197608272011011001,199303122015071001,198307172001121001,199110292020121008,199205182015071003,198502102006021001,197703152010011004,197805192009021002,197906101999031004,199201152014061001,197602092007011008,198802102011011002,198605242014021001,198205272005012008,199208112015071001,199302192015071001,197205282005011004,198108122009012006,198306172006041001,199503052017082001,199308152015071002,197910032010011003,197712052011011001,197204052008011004,197309132007011004,197712092008011002,198907142014021002,196810132014091002,197105172007011007,198404052015031003,199107192015031006,198505052004122001,199203282014062001,199709152019082001,199106012013101001,198904042020122020,197505172010011009,197812152000122004,198204012009011002,197904172014101002,197301291993031003,199407062019032017,198708262011011001,198109032009012002,199708162020122011,199106022015031001,197612032002121005,197606302010011002,198409302009022005,197906022010011012,197212112014092001,198604022011011003,198111142010011005,199404112016092001,197612071996031001,198005232024212004,197102261990031001,197602252006041003,197808282011012001,199412172022031011,198105012010012002,199210012020121018,197408152009012002,196902182008011002,199003012020121009,196903021989032002,197806282009011001,198908222014032003,198601102009021001,197612041997031002,198202062006041011,198502062009022003,199010032010101001,197007171991032006,198605252014121001,197507242010011007,197509241996031003,198010052009011002,199412222017081001,199210022025051001,198704062011012003,197808202009011002,197307012014111001,197004072007011009,197711291999011001,197008101997031005,198007042005011010,197509012000031002,197910311999031004,198802172007012001,197512092008012002,198004022000031001,198610192011011003,197804112006041010,197206251992121001,197701172009021004,198103292009121003,197910091999031002,198505232015032004,198106182009121002,196902041998031004,197709182011011006,198106182012121004,197707121997031002,198305052009022003,197703182011011001,197206072009011001,197009271997031006,197202211998031002,198406052010011012,197108021998031007,198111152010011008,198802212012112001,196804081998031002,198304182010121004,197205022007011011,197407082006041006,196911141998031005,196910301998031004,196904201998031002,197211112006041005,197412182000031003,197203252000031007,197107071998031007,197801242009021002,197611282011011001,197605202000032003,198212012010011002,199509032020121011,197410192009011001,197002041998031005,196808161998031005,198008082011011003,196904171998031007,197601142009011006,198011152000031001,197611042007012004,197106251998032004,197110211998031007,196805071994031007,196805051998031011,197606162011011001,198105092011011002,198203092015032002,198604302010012013,198312122015031002,197907282008011002,19710808199

In [70]:
# Save in text file
with open('all_nips.txt', 'w') as file:
    file.write(nip_all_str)